### ISSUE TITLE
Translate source code comments

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/px68k-libretro#100]
I am happy to translate the source code comments from Japanese to English if that would be of help?

I plan to duplicate the comment, so we have original Japanese text next to translated English text

Request here: 
https://github.com/libretro/px68k-libretro/pull/97#issuecomment-571587111

**Comment by negativeExponent** [comment]
if you have a discord account, you can probably join the libretro' discord channel. at least one guy there, **hasenbanck**, offers to help with the translation.

we should probably translate one source at a time, drop the japanese text(i think leaving this text on utf8 is a problem on some platforms?) and just go with English translations and convert the file to whatever encoding is safer.

**Comment by gingerbeardman** [comment]
Well, the PR about encoding had some questions regarding compilers I cannot answer. So I think that needs answering first before I start with this, just to avoid unnecessary work.

I am happy and able to translate the Japanese.

**Comment by gingerbeardman** [comment]
PS: I am already on the libretro discord as "gingerbeardman"

**Comment by negativeExponent** [comment]
we really should get this going. maybe for now translate just the main source files to utf8 and do translation later. I don't know how good you japanese is buy mine sucks.

(read my post on the now closed unmerged PR)

**Comment by negativeExponent** [comment]
This plan is no longer viable. Debug notes and untranslated text sadly removed....

**Comment by gingerbeardman** [comment]
@negativeExponent really sad to read that all comments have been removed. what is your reasoning @twinaphex ?

**Comment by negativeExponent** [comment]
A lot of stuff removed. Even source files and the option to r3create the c68k opcode tables when you need to for whatever reasons. 

It cant be a 'libretro core' without removing a whole lot of stuff. Probably translation would probably  hav been a waste of our effort, since the untranslated texts are debug and dev comments, which being a core, comments and logging will just be removed anyways.

**Comment by twinaphex** [comment]
It has been an entire year during which that time these translations could have been done. It never happened. 

If you still want to translate those comments and put them back in, by all means. but if they are just going to rot away like that for years and the burden and expectation is on us ourselves to translate it, well we dont have time or interest for that, so out it goes.

Again, if you want to put them back in and translate them along the way, go ahead and send a pull request. Just dont expect me to do it.

**Comment by twinaphex** [comment]
I will reopen this just this once in case people actually want to start getting serious about this issue instead of just talking about it. Bottomline is that if you want to see all this stuff done, you need to put some effort in and send the PR. Its as simple as that.

**Comment by twinaphex** [comment]
Since I rolled back all the changes now, nothing should be preventing you from translating these strings now. Time for some action.

**Comment by gingerbeardman** [comment]
I can and will translate the comments, no problem at all. 

The issue that was unresolved was how to deal with the encoding, you were worried that changing the encoding of the files could break the build and I am not in a position to be able to test that. 

If the encoding changes are given the OK, in whatever way makes sense, I will begin the translation of comments.

ps: These days for Japanese text I use [CotEditor](https://www.coteditor.com) (macOS only) that is Japanese and understands and respects these old encodings.

**Comment by LibretroAdmin** [comment]
This didn't seem to go anywhere, so closing for now. If someone still wants to add back the comments, send a PR.

**Comment by gingerbeardman** [comment]
For the record: the thing that didn't go anywhere was a solution to the issue of line ending changes.
