### ISSUE TITLE
Translate in-emulator menu 

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/px68k-libretro#101]
The in-emulator menu is currently in Japanese.

A while ago I did an English translation:

[menu_str_sjis_en.txt](https://github.com/libretro/px68k-libretro/files/4032356/menu_str_sjis_en.txt) (Shift-JIS text encoding)

[menu_str_utf8_en.txt](https://github.com/libretro/px68k-libretro/files/4032355/menu_str_utf8_en.txt) (UTF-8 text encoding)

Request here:
https://github.com/libretro/px68k-libretro/pull/97#issuecomment-571587111

What do we feel is the best method of including this?

It feels kind of bad to overwrite the original translation, so my thoughts were to make this selectable, then we have volunteers willing to translate into other languages, eg. French. But then, are we focussing efforts on the emulator core code rather than the libretro code?

So perhaps it's better to do as #62 and transfer all these in-emulator options into the RetroArch core options interface?

Any thoughts @twinaphex ?

**Comment by negativeExponent** [comment]
menu is already translated https://github.com/libretro/px68k-libretro/blob/master/libretro/windraw.c#L1140
