### ISSUE TITLE
Widgets (messages text) crappy font

### ISSUE THREAD

**Issue by Darknior** [libretro/px68k-libretro#109]
Hi,
I think retroarch changed something on widgets - which are messages text - and this cores has not been updated :(
On some core the background is missing, and font is yellow, here background is fine but text is dark and impossible to read it :(

![20200118_132627_HDR](https://user-images.githubusercontent.com/3703317/72664269-1b40e100-39fc-11ea-9f9d-0a65ce1a0b84.jpg)

Is it possible to fix this problem please ?
Thanks a lot

**Comment by negativeExponent** [comment]
widgets are not part of any core, this should be posted on retroarch

**Comment by Darknior** [comment]
Are you sure ? because it depend of core ... on some it works fine on other we have different bugs ...
If you are sure can you give me where i must report them ?
I have some core to report, not only this one.
Thanks

**Comment by Darknior** [comment]
I've post here https://github.com/libretro/RetroArch/issues/10026
I wish some one will answer me but that's strange the bug on x68000 was different ...
