### ISSUE TITLE
[Discussion for implementation] Map extra keys to gamepad

### ISSUE THREAD

**Issue by negativeExponent** [libretro/px68k-libretro#111]
Anyone more familiar with the system, specifically which games requires more than 2 button (excluding obvious 6/8 button gamepad games like street fighter etc)

The plan is to map some commonly used keyboard keys to the standard 2-button mapping. The current 2-button mapping will be remade, removing X/Y assignments and utilizing core options to swap button layout if needed, and an alternate vertical button layout(which i prefer). This will then give use free buttons to use (X, Y, L, R, L2, R2, L3, R3 even the analogs can be utilized)

XF1 for example is used for Chelnov to change where your character is facing.
I think a Mario clone uses OPT1 for Start
F1/F2 is used for Parodius Da for P1/P2 start

The lucky key candidates are probably the ones already on the "Select hotkey core option"
https://github.com/libretro/px68k-libretro/blob/7aaa64ee434f8bae0d2b6695744279a60e889263/libretro_core_options.h#L147-L155

Other keys are welcome.

**Comment by Darknior** [comment]
Sorry i don't have configure many games for the moment, i will do it in a near future ... and then i don't have other keys in mind for the moment.
But i love the idea, it's what i dream to have to configure games better on joypad :)
Thanks a lot

**Comment by gingerbeardman** [comment]
I'll look at some games that I play soon.

**Comment by negativeExponent** [comment]
UPDATE:
other gamepad buttons viable for a key remap:
- left/right thumbsticks
- L3/R3 in thumbsticks
- L1/L2
- R2 (pending PR set to SCROLL_LOCK key (touroku)
