### ISSUE TITLE
In-emu file picker should honour path of most recently loaded file

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/px68k-libretro#114]
In-emu file picker should honour path of most recently loaded file

## Repro
1. Load floppy disk image through RetroArch menu

2. Open in-emu menu

> ![Screen shot 2020-01-21 at 15 24 30](https://user-images.githubusercontent.com/49612/72817715-25fcaf80-3c62-11ea-843b-8a0eedeac1c7.png)

3. Press Enter on FD0 to get file picker

Also
1. Load FD0 image through in-emu menu
2. Press Enter on FD1 to get file picker

## Expected
- in-emu picker should get path from last loaded file

- by setting `StartDir` in config?

## Actual
- in-emu picker defaults to root /

> ![Screen shot 2020-01-21 at 15 20 31](https://user-images.githubusercontent.com/49612/72817539-dae29c80-3c61-11ea-87c3-ffcb74d3c18e.png)

**Comment by negativeExponent** [comment]
im not sure why i did not push through with this idea. im sure i was thinking of adding such feature. ill revisit this sometime soon

**Comment by negativeExponent** [comment]
The best case will be: 
:if the fdd0 or is not empty, then opening the drive would start you in the sir when the rom is located.
:ejecting the drive would bring you to StartDir if set. It would be nice to start on dir where the last loaded rom was. I'll see how to implement this.

**Comment by negativeExponent** [comment]
@gingerbeardman btw, do you happen to know any more .hds titles? all i can fine is just one compilation from gamesx. cant find any other .hds files. i would like to look at this feature further.

**Comment by gingerbeardman** [comment]
Compilation HDS files here: https://nfggames.com/X68000/index.php/Games/
- Mini
- MiniV2 
- X68000_MDX
- X68000+V2,3,4

There are some individual game HDS files in the Neo Kobe pack:
https://archive.org/download/SharpX68000Collection or https://archive.org/download/Sharp_X68000_Collection I *think* they are the same?

Directory listing of that: [Neo Kobe - Sharp X68000.txt](https://github.com/libretro/px68k-libretro/files/9683779/Neo.Kobe.-.Sharp.X68000.txt)

**Comment by negativeExponent** [comment]
thanks

**Comment by gingerbeardman** [comment]
> @gingerbeardman btw, do you happen to know any more .hds titles? all i can fine is just one compilation from gamesx. cant find any other .hds files. i would like to look at this feature further.

old comment, but am I thinking this emulator just doesn't support the HDS (SCSI) format of disk images? That they are a different format than HDF (ACSI) format? Even if we added file extension support it still wouldn't work?

**Comment by negativeExponent** [comment]
@gingerbeardman 

late reply. HDS is SCSI while HDF is SASI, totally different hardware not to mention the default code in px68k does not support SCSI devices.

TutleBazooka appears to have SCSI support for his px68k fork. you may want to ask him if his interested to add it to this fork..

now back to this topic. Im working on this next and already figured out a way to keep last directory upon eject of disk. whats the ideal behavior though? keep floppy drives A/B in sync with the last dir and HDD0/HDD1 as well? or each drive keeps its own last directory.

**Comment by gingerbeardman** [comment]
I think just one for all

**Comment by negativeExponent** [comment]
pushed commit. just reopen if we need this adjusted or needs fixing somewhere.
