### ISSUE TITLE
Pressing left and right simultaneously pauses ChoRenSha 68K

### ISSUE THREAD

**Issue by UltraHex** [libretro/px68k-libretro#123]

**Comment by negativeExponent** [comment]
https://github.com/libretro/px68k-libretro/blob/master/libretro/joystick.c#L141
select acts as pause in chorensha, which is just a macro to left+right

**Comment by UltraHex** [comment]
Is there a way to disable the macro?

**Comment by negativeExponent** [comment]
ill see what i can do. but i cant implement anything for this core at this time...

**Comment by negativeExponent** [comment]
this behavior should now be prevented in latest commit https://github.com/libretro/px68k-libretro/commit/5296e4b93b007df7abb325bce55275d2e6a82b62
