### ISSUE TITLE
SIGSEGV (Address boundary error) with Etoile Princess

### ISSUE THREAD

**Issue by ghost** [libretro/px68k-libretro#135]
When running the game Etoile Princess using:

``retroarch -L ~/.config/retroarch/cores/px68k_libretro.so  Etoile\ Princess.m3u``

after the title screen, retroarch exists with 

``fish: 'retroarch -L ~/.config/retroarc…' terminated by signal SIGSEGV (Address boundary error)``

Using:
- dim files from https://archive.org/download/SharpX68000RomCollectionByGhostware/Etoile%20Princess.zip
- current master build 8455d9c
- Linux 5.10.13-arch1-1 #1 SMP PREEMPT Wed, 03 Feb 2021 23:44:07 +0000 x86_64 GNU/Linux

**Comment by negativeExponent** [comment]
i cant even get the game to play consistently, regardless of any method used to load even just the system disk. its one of those games thats incompatible.

**Comment by negativeExponent** [comment]
you may want to try this on latest commit, seems to have resolved itself in my case at least (using both m3u mentod, and manual loading of disks from px68k menu (f12)).

**Comment by maxoblasto** [comment]
Tried this in retroarch 1.9.6 on the latest px68k commit version (16d59eb) but I'm still getting the issue where it shows the opening splash screen then immediately crashes. Tried both loading the core then loading the m3u through retroarch as well as starting the core and manually loading both disks.

**Comment by sarahwhitman** [comment]
I'm running into this issue as well, and I've attached the verbose output and crash log:

[crash-210801-021745.log](https://github.com/libretro/px68k-libretro/files/6912425/crash-210801-021745.log)
[crash-210801-021745-verbose.log](https://github.com/libretro/px68k-libretro/files/6912426/crash-210801-021745-verbose.log)

**Comment by gingerbeardman** [comment]
Works for me.

0. insert first two discs into FD0 & FD1
1. System Disk
2. splash screen
3. Menu
4. intro with music and scroll text
5. and we're into the game

core downloaded today
RA 1.9.7
macOS Bug Sur

So maybe check all your BIOS files?

**Comment by sarahwhitman** [comment]
My BIOS files have the correct hashes. I tried the alternate BIOS files (iplrom30.dat, iplromco.dat, etc.) but no luck. I usually load multi-disk games like these via m3u playlist, but I tried manually loading and then starting the core, inserting the system disk and the "Data 1" disk, one at a time, then a reset, but that gives the same result. I've also tried a number of different core option configurations and alternate Etoile Princess diskette files.

The result is always the same, a brief intro animation with the spinning gold star/intro text, fade to black, and then a retroarch crash. FWIW I do not have scrolling text or music on the intro screen, only static text and silence.

- core downloaded today
- RA 1.9.6
- Windows 10 x64 17763.2090

**Comment by gingerbeardman** [comment]
Is this from a clean RA install? As in, try deleting (or temporarily moving) your prefs.

**Comment by gingerbeardman** [comment]
You only seem to be getting to Splash screen, with 3D star, not even to menu/intro/game.

The first sound only happens when you get to the menu and choose an item, there is a twinkle sound effect.

Intro is of a castle with distant waterfall, after a moment some scroll text appears at the bottom.

Here's a video (no sound, my recording problem) of me launching it:
https://youtu.be/7gO0hR_ekRQ

**Comment by sarahwhitman** [comment]
Thank you for confirming on your end, I see now what the correct behavior looks like. Every change I've made has resulted in a hard crash at about 0:19 in your video -- confirming that the crash still occurs even with a fresh retroarch.cfg and after temporarily moving everything in retroarch\config\PX68K

**Comment by gingerbeardman** [comment]
My pleasure. It's annoying when things don't work as expected.

After the fade-to-black at 0:19 that you describe it is still loading from FD0 (System disc). Only after menu is chosen does it load from FD1 (let's call it second disk). 

With the wrong disc in you would see:

<img width="1080" alt="Screen shot 2021-08-04 at 22 33 35" src="https://user-images.githubusercontent.com/49612/128257940-08ea98b1-610a-468e-b0c7-c5044c3d75b4.png">

**Comment by sarahwhitman** [comment]
Right, it is definitely not touching FD1, I have tried manually loading only the game's system disk by itself, and see the exact same crash behavior. FWIW there are several Etoile Princess system disk images floating around:

- Etoile Princess (1993)(Exact)(Disk 1 of 3)(System).dim  --  crc32: 98012AA4 (this is the one that Mame recognizes)
- Etoile Princess (1993)(Exact)(Disk 1 of 3)(System)[a].dim  --  crc32: 94902BDB
- Etoile Princess (1993)(Exact)(Disk 1 of 3)(System)[a2].dim  --  crc32: E6AF0B35

I just tested all three system disk images (only using Fdd0, nothing in Fdd1) and have the crashing issue with all of them. There is a fourth system-disk image floating around but I haven't been able to locate a copy to test:

- Etoile Princesse [Disk 0] (y) (Exact) [xdf].xdf  --  crc32: 7540a5a1

**Comment by gingerbeardman** [comment]
I am wondering if this is an endian issue?

I'll try to test on other platforms. I have Switch and N3DS, not sure about the availability of PX68K on either of those.

**Comment by gingerbeardman** [comment]
So I just booted up an old Windows 10 VM running RA 1.9.0 and PX68K 0.15+ 4ca8974 (13 December 2020)

Etoile Princess runs fine: https://youtu.be/BWqtGBfg2zw

Here's the old core just in case it's that: 
[px68k_libretro_4ca8974_20201213.zip](https://github.com/libretro/px68k-libretro/files/6945149/px68k_libretro_4ca8974_20201213.zip)

But I think you have problems elsewhere in your setup.

**Comment by maxoblasto** [comment]
Thanks a bunch for the link to the old core. Works for me using it now.

**Comment by Tatsuya79** [comment]
Working fine on Hunterk builds:
https://github.com/hunterk/libretro_builds

**Comment by gingerbeardman** [comment]
Exciting times for X68K emulation!

**Comment by Tatsuya79** [comment]
Looks like it has been fixed by today's changes.

**Comment by LibretroAdmin** [comment]
Cool to hear this is now resolved.

**Comment by Nahojii** [comment]
This is still an issue on current versions.
