### ISSUE TITLE
Several problems with this core

### ISSUE THREAD

**Issue by AlanRibas** [libretro/px68k-libretro#138]
I tried to play a game but I just couldn't do it. 
Most games start but there is only a black screen on the screen. We can hear the sound of the game, but that's it.
The few games that the image appears on the controls do not work. I have an Xbox 360 joystick here and it is not recognized in that core. I tried to change the control mode for the computer keyboard but there is still no response.

I used to play games in this core, like "Akumajou Dracula" for example. But this also enters the group of games that the image no longer appears.

**Comment by negativeExponent** [comment]
core haven't been changed for awhile now. theres just no reason, core-related, that it would just not work when it worked before. reset your ra settings, core settings etc.

**Comment by AlanRibas** [comment]
> core haven't been changed for awhile now. theres just no reason, core-related, that it would just not work when it worked before. reset your ra settings, core settings etc.

How do I reset the settings for that core only?

**Comment by gingerbeardman** [comment]
you will need to delete any lines in `retroarch-core-options.cfg` that begin with the name of the core

**Comment by AlanRibas** [comment]
> you will need to delete any lines in `retroarch-core-options.cfg` that begin with the name of the core
> 
> i'm not aware of a way to do it from within RA
> 
> example
> 
> <img alt="Screen shot 2021-05-12 at 21 15 33" width="753" src="https://user-images.githubusercontent.com/49612/118038592-3a891d80-b367-11eb-9eae-17373ff33b66.png">

I deleted the file at this address: "PX68K.opt"

D: \ Games \ RetroArch \ config \ PX68K

ONLY THAT NOTHING HAS CHANGED .....

Can anyone confirm for me that the game AKAMAJOU DRACULA works on your computers?

**Comment by negativeExponent** [comment]
- find where your "retroarch's system" folder is located
- goto "system/keropi"
- delete "sram.dat"

see if that helps
and the question regarding if this core works, Yes it still does...

if it still does not, then still on <retroarch>/system/keropi, and delete "config" file

post logs as well

**Comment by negativeExponent** [comment]
sorry accidentally pressed "close with comment"

**Comment by AlanRibas** [comment]
I deleted these two files but the black screen remains.
Whenever I enter the game it goes to that part (photo below). I choose option number 1. Right after that, a game song starts. The music is playing but no image appears.

![WhatsApp Image 2021-05-12 at 22 22 29](https://user-images.githubusercontent.com/16063712/118064246-061a5f00-b371-11eb-9ec7-a5b59ec4ae08.jpeg)

**Comment by negativeExponent** [comment]
if you ever only tested with akumajou dracula and not other games, then its probably a bad disk, specifically disk 2. anyways this is the only game i play on this core and mine works, 2fdd version and the hdf one.

**Comment by AlanRibas** [comment]
> if you ever only tested with akumajou dracula and not other games, then its probably a bad disk, specifically disk 2. anyways this is the only game i play on this core and mine works, 2fdd version and the hdf one.

I will then download the roms from a more reliable location and do a test now.

**Comment by AlanRibas** [comment]
I downloaded the roms from the trusted site that I commented on. I tested it compacted, unzipped. Nothing worked.

**Comment by negativeExponent** [comment]
from your log: 
`Using content: D:\Jogos\EMULADORES\X68000\Roms (X68000)\Akumajou Dracula.zip`

you dont load disk unto this core using compressed format...

https://docs.libretro.com/library/px68k/

**Comment by AlanRibas** [comment]
> from your log:
> `Using content: D:\Jogos\EMULADORES\X68000\Roms (X68000)\Akumajou Dracula.zip`
> 
> you dont load disk unto this core using compressed format...
> 
> your "other" games worked because either the compressed file only contain a single-disk game or its a multidisk, BUT you can play with just disk 1.
> 
> Akumajou Dracula for example uses 2 disks, without the 2nd disk inserted, you get black screen while the music continuous to play.
> 
> https://docs.libretro.com/library/px68k/
> 
> You also need to select option 1 from that screenshot you posted.

I understood.
I've already unpacked all my roms.
But even when unzipped when starting the game, I choose, in my case "Akumajou Dracula (Disk 1 of 2) .dim". How do I insert the second disc once the first one starts?

Using the emulator mentioned above I actually did this insertion manually. I thought RetroArch was able to do that automatically. But thanks to you it was clarified that no.

**Comment by gingerbeardman** [comment]
Create a file

`Akumajou Dracula.m3u`

containing the following two lines

```
Akumajou Dracula (Disk 1 of 2) .dim
Akumajou Dracula (Disk 2 of 2) .dim
```

Then choose the .m3u from RA and it will insert both disks automatically.

There is a manual way to insert disk B after choosing disk A, but I don't recommend that.

**Comment by AlanRibas** [comment]
Thank you very much for the explanations. It's working perfectly now.

And thanks to everyone who worked to help me.

One last question before closing this topic.

A game I have here called "A-Jax". Did not work.
I created the .m3u file:
A Jax (Disk 1 of 3) (Program) .dim
A Jax (Disk 2 of 3) (Disk 1) .dim
A Jax (Disk 3 of 3) (Disk 2) .dim

I tried to remove the first file "A Jax (Disk 1 of 3) (Program) .dim".

I tried to rename it to:
A Jax (Disk 1 of 3) .dim
A Jax (Disk 2 of 3) .dim
A Jax (Disk 3 of 3) .dim

But the screen below always appears.


![WhatsApp Image 2021-05-14 at 13 35 04](https://user-images.githubusercontent.com/16063712/118301768-d460df80-b4b9-11eb-8aff-a20e94821ee7.jpeg)

**Comment by gingerbeardman** [comment]
The X68000 computer only has two disk drives, A and B, so in real life you would "juggle" the discs ejecting and replacing as the game requires. Here I think it's asking for disk 2.

But using your .m3u you only have the first two disks inserted (A: program disk, B disk 2 of 3 which is disk 1) so disk 3 of 3 (disk 2!) is not yet inserted.

This case you need to cycle between the discs using RA disk control option.

This answer talks about swapping discs for PlayStation, but the same applies here: https://www.reddit.com/r/PlaystationClassic/comments/alut7g/multi_disc_games_ff7_re2_mgs_etc_and_retroarch/efhb8ee

**Comment by AlanRibas** [comment]
> The X68000 computer only has two disk drives, A and B, so in real life you would "juggle" the discs ejecting and inserting disks as the game requires. Here the game is asking for disk 2 (which is 3 of 3).
> 
> But using your .m3u you only have the first two disks inserted (A: program disk, B disk 2 of 3, aka disk 1) so disk 3 of 3 (aka disk 2!) is not yet inserted.
> 
> This case you need to cycle between the disks in the m3u using RA "disk control" options.
> 
> This answer talks about swapping discs for PlayStation, but the same applies here: https://www.reddit.com/r/PlaystationClassic/comments/alut7g/multi_disc_games_ff7_re2_mgs_etc_and_retroarch/efhb8ee
> 
> and this video shows https://youtu.be/aSSGrAViJTw?t=383


Thank you very much. I'll try that.

And thank you all for your help !!!
