### ISSUE TITLE
Convert multiple files into one

### ISSUE THREAD

**Issue by AlanRibas** [libretro/px68k-libretro#141]
I was researching the internet and I came across information that said it was possible to convert the multiple diskettes of the x68000 system games into a single file. But I did not understand the process well.

Do you know if this is possible?

I recently unzipped my roms to work right in the core of this emulator and I came across several different types of files.

.dim
.xdf
.hdf

in some cases the compressed game file has more than one extension shown above. I am in doubt of what to keep and what I can disregard and delete.

**Comment by gingerbeardman** [comment]
This is to convert floppy disk images into hard disk images. So it's installing a game to hard drive. That should help you find a guide or YouTube video. 

Ps: This is not the best place to ask for support issues. Use RetroArch form and tag me, user name: matt

**Comment by AlanRibas** [comment]
> 
> 
> This is to convert floppy disk images into hard disk images. So it's installing a game to hard drive. That should help you find a guide or YouTube video.
> 
> Ps: This is not the best place to ask for support issues. Use RetroArch form and tag me, user name: matt

Sorry but I did not understand exactly where I should make this record of doubt. Could you show me a link?

**Comment by gingerbeardman** [comment]
Sorry I mistyped. RetroArch forum

https://forums.libretro.com/

**Comment by AlanRibas** [comment]
> Sorry I mistyped. RetroArch forum
> 
> https://forums.libretro.com/

Thank you very much for the tip gingerbeardman. I will close this topic and open another one at this address that you recommended to me.

Down is already his link ..

https://forums.libretro.com/t/convert-multiple-files-into-one-x68000/33384

Thank you for your help.
