### ISSUE TITLE
Feature Request: Full Analog Support

### ISSUE THREAD

**Issue by TideGear** [libretro/px68k-libretro#142]
Currently, analog support seems to be broken as there's no way to map the analog stick of a controller (e.g. a 360 controller) to act as an x68k analog stick. Support for an analog rudder (like the "Cyber Stick" has) (see attached image)would be great too! 
![s-l400](https://user-images.githubusercontent.com/16357059/122335308-e934f680-ceef-11eb-8912-cbeac4179a41.jpg)

**Comment by gingerbeardman** [comment]
Which games can be used to test analog support?

**Comment by TideGear** [comment]
Star Luster and Star Cruiser are two off the top of my head. I think SL even has the analog rudder support.

**Comment by negativeExponent** [comment]
its not a bug, per se. this controller was never implemented to begin with, more like a feature/support request.

Ive though this controller was somewhat just a basic controller + analog support (aka mouse), which can be demonstrated on Afterburner. But overtake has an option to use CyberStick, and selecting so will just revert to Digital instead, so it seems like a register or mode is still missing for correct detection (like detecting from a 2 vs 6/8 button joysticks)

**Comment by TideGear** [comment]
> its not a bug, per se. this controller was never implemented to begin with, more like a feature/support request.
> 
> Ive though this controller was somewhat just a basic controller + analog support (aka mouse), which can be demonstrated on Afterburner. But overtake has an option to use CyberStick, and selecting so will just revert to Digital instead, so it seems like a register or mode is still missing for correct detection (like detecting from a 2 vs 6/8 button joysticks)

Thanks, negative. I've changed the title accordingly. Are you a dev capable of adding this?

**Comment by negativeExponent** [comment]
no

**Comment by gingerbeardman** [comment]
I'm happy to give it a go, but I think we would need documentation how this type of controller is seen/processed at a hardware level on original hardware.

**Comment by negativeExponent** [comment]
not at this time. if there are documentations, its in japanese

**Comment by negativeExponent** [comment]
preliminary work for cyberstick analog/digital support is added.

https://github.com/libretro/px68k-libretro/pull/186/commits/90887d6ed7c32c28fc67c81bbf783630499ce8ad

its a basic implementation but seems to work in most titles that supports the controller type.

Only player port 1 (port 0) supports it. and may need to set MPU clock to 16Mhz. Overtake buttons appear to randomly click itself when clock is higher in some cases.
