### ISSUE TITLE
M3U not work under Retroarch 1.9.5

### ISSUE THREAD

**Issue by handlolo** [libretro/px68k-libretro#144]
Appear a quote under the selected disk in FDD0 when you select a m3u with Multidisk
(text in config file of emulator)
FDD0="/opt/systems/x68000/Akumajou Dracula (1993)(Konami)(Disk 1 of 2).dim"
FDD1=
And the multidisk games not work

**Comment by negativeExponent** [comment]
i dont even understand what you are trying to do, and/or why. There are simplier ways to run multidisk.

**Comment by gingerbeardman** [comment]
@handlolo M3U should contain only filenames, one per line, with no other text.

See: https://docs.libretro.com/library/px68k/

**Comment by handlolo** [comment]
Content of the Akumajou Dracula.m3u: 
Akumajou Dracula (1993)(Konami)(Disk 1 of 2).dim
Akumajou Dracula (1993)(Konami)(Disk 2 of 2).dim

Since retroarch 1.9.3, the m3u multidisc dont work, only work the m3u with a single disk

**Comment by handlolo** [comment]
> i dont even understand what you are trying to do, and/or why. There are simplier ways to run multidisk.

Im trying to run a m3u, after update Retroarch 1.9.3, the multidisk m3u files dont work, appear the problem that i write more up.

**Comment by negativeExponent** [comment]
ok managed to recreate the "not working issue using m3u"

this has got nothing to do with the core itself, but if you got your cores from buildbot, then the core is not working. Verified using akumajo disks on m3u as reported. Woks fine with locally compiled core using the same committ, but core from updater/builbot not working, the same issue i kept reporting so many months ago that fell on deaf ears, first discovered by @gingerbeardman on MacOS.

@hunterk @twinaphex

**Comment by hizzlekizzle** [comment]
@negativeExponent can you link us to that previous issue or refresh us on the circumstances?

**Comment by gingerbeardman** [comment]
I believe it's this old one of mine: https://github.com/libretro/px68k-libretro/issues/121

**Comment by handlolo** [comment]
@gingerbeardman? What values did you change in the sources when compiling it, to work??.
 I have tried to compile it and it keeps failing in the same way

**Comment by gingerbeardman** [comment]
I did not make any changes.

**Comment by negativeExponent** [comment]
what system did you use and what compiler version

**Comment by handlolo** [comment]
> what system did you use and what compiler version

Ubuntu 18.04 and GCC 8

**Comment by negativeExponent** [comment]
not sure if this is related to @gingerbeardman issue, but i've found whats causing this problem on m3u at least. depending on the compiler, the parsing of the arguments in is not working in some compilers. e.g:

buildbot (see, logs are really helpful...):
```[libretro INFO] Loading from an m3u file ...
[libretro INFO] index 1: /mnt/data/emulator/x68000/Akumajou Dracula (1993)(Konami)/Akumajou Dracula (1993)(Konami)(Disk 1 of 2).dim
[libretro INFO] index 2: /mnt/data/emulator/x68000/Akumajou Dracula (1993)(Konami)/Akumajou Dracula (1993)(Konami)(Disk 2 of 2).dim
[libretro INFO] Parsing arguments ...
[libretro INFO] 0 : px68k
[libretro INFO] 1 :  "/mnt/data/emulator/x68000/Akumajou Dracula (1993)(Konami)/Akumajou Dracula (1993)(Konami)(Disk 2 of 2).dim"
[libretro INFO] PX68K Ver."0.15+"
[libretro INFO] Libretro...
[libretro INFO] /home/negative/.config/retroarch/system/keropi
[libretro INFO] cur_dir_str / 1
[libretro INFO] fp:1302559648 (iplrom.dat)
[libretro INFO] R: f800, G: 7e0, B: 1f
[libretro INFO] Restarting PX68K...
[libretro INFO] INIT done
```
see it loading disk2 instead or disk 1 and then disk 2 on "Parsing arguments?"

while locally compiled core (gcc 11.x) looks like this
```[libretro INFO] Loading from an m3u file ...
[libretro INFO] index 1: /mnt/data/emulator/x68000/Akumajou Dracula (1993)(Konami)/Akumajou Dracula (1993)(Konami)(Disk 1 of 2).dim
[libretro INFO] index 2: /mnt/data/emulator/x68000/Akumajou Dracula (1993)(Konami)/Akumajou Dracula (1993)(Konami)(Disk 2 of 2).dim
[libretro INFO] Parsing arguments ...
[libretro INFO] 0 : px68k
[libretro INFO] 1 : /mnt/data/emulator/x68000/Akumajou Dracula (1993)(Konami)/Akumajou Dracula (1993)(Konami)(Disk 1 of 2).dim
[libretro INFO] 2 : /mnt/data/emulator/x68000/Akumajou Dracula (1993)(Konami)/Akumajou Dracula (1993)(Konami)(Disk 2 of 2).dim
[libretro INFO] PX68K Ver."0.15+"
[libretro INFO] Libretro...
[libretro INFO] /home/negative/.config/retroarch/system/keropi
[libretro INFO] cur_dir_str / 1
[libretro INFO] fp:-1916575472 (iplrom.dat)
[libretro INFO] R: f800, G: 7e0, B: 1f
[libretro INFO] Restarting PX68K...
[libretro INFO] INIT done
```

**Comment by negativeExponent** [comment]
> > what system did you use and what compiler version
> 
> Ubuntu 18.04 and GCC 8

try recompiling px68k core, and recompile retroarch as well using gcc8

**Comment by negativeExponent** [comment]
well the logging PR i added did not help pinpoint the issue, its just everywhere. Strings are just getting broken, wether loading from command line, using CMD file format or M3U.

for example, if you hardcode the rompaths directly in <system>/keropi/config like so:
```
FDD0=/mnt/data/emulator/x68000/Akumajou Dracula (1993)(Konami)(Disk 1 of 2).dim
FDD1=/mnt/data/emulator/x68000/Akumajou Dracula (1993)(Konami)(Disk 2 of 2).dim
```
then load the core without content, which will bring up its px68k menu, core will just load and mount disks using basenames, and not the actual path like so:
![image](https://user-images.githubusercontent.com/54053706/123527468-72c79e00-d712-11eb-9ee4-82168ca98856.png)

someone with better experience with string handling should be able to fix this faster (of probably compiler flags or whatever?)

in my case though, without a working environment where this problem can ne replicated, then i cant go on guessing where issue is and sending multiple PR(since its only on buildbot that this happens)

@hunterk

**Comment by hizzlekizzle** [comment]
oh no, sounds spooky :(

Thanks for looking into it, @negativeExponent . So, buildbot core works with current RetroArch built on old Ubuntu? Did you use the same gcc version for both RetroArch builds?

**Comment by negativeExponent** [comment]
i may have pinpoint it at a very scope at the moment. trying something one last time.

**Comment by negativeExponent** [comment]
took about 5 hours for buildbot core to appear....

But core from buildbot should now be working. please confirm guys, so the debug logs can be taken out...

**Comment by handlolo** [comment]
> took about 5 hours for buildbot core to appear....
> 
> But core from buildbot should now be working. please confirm guys, so the debug logs can be taken out...

Works perfect!! a lot of thanks @negativeExponent

**Comment by negativeExponent** [comment]
> > took about 5 hours for buildbot core to appear....
> > But core from buildbot should now be working. please confirm guys, so the debug logs can be taken out...
> 
> Works perfect!! a lot of thanks @negativeExponent

thanks for the confirmation and report...

**Comment by negativeExponent** [comment]
fixed in https://github.com/libretro/px68k-libretro/commit/f336717f71bacbb1003aba3485b70034261cd230

**Comment by gingerbeardman** [comment]
nice work!
