### ISSUE TITLE
[Enhancement] Relative path support in cmd file

### ISSUE THREAD

**Issue by zach-morris** [libretro/px68k-libretro#148]
If possible, it would be great if the cmd file loading supported relative paths.

Example:
Game Files:
```
path_to_game/Full Throttle/
path_to_game/Full Throttle/Full Throttle (Disk A).dim
path_to_game/Full Throttle/Full Throttle (Disk B).dim
path_to_game/Full Throttle/Full Throttle.cmd
```

Currently, if the cmd file contains:
```
px68k "path_to_game/Full Throttle/Full Throttle (Disk A).dim" "path_to_game/Full Throttle/Full Throttle (Disk B).dim"
```

The game loads, but if the file contains paths relative to the cmd file, it doesn't work:
```
px68k "./Full Throttle (Disk A).dim" "./Full Throttle (Disk B).dim"
```

Supporting relative paths would make the cmd file and the game file(s) more portable

**Comment by negativeExponent** [comment]
this should now be supported in the pending PR when that gets merged
