### ISSUE TITLE
"config" file being completely ignored

### ISSUE THREAD

**Issue by bslenul** [libretro/px68k-libretro#153]
Hey!

Currently the `retroarch/system/keropi/config` file is not being created anymore, and even if you have one from a previous version of the core, it's not being read. So a super useful line like `StartDir=` can't be used anymore :/ 

Already bisected, this is the 1st bad commit: 53a1d027ce3e3b991d2a535906b171be7a6a3d4f .

**Comment by negativeExponent** [comment]
ive doubt this wil even be restored. even loggings are removed. core now broken, buildbot core still even is broken.

**Comment by twinaphex** [comment]
It should be properly implemented as core options instead of reading from a config file. We dont want all these external config files and we dont want the file I/O that comes with it.

**Comment by negativeExponent** [comment]
You can't set a starting path from core options!!!....

**Comment by bslenul** [comment]
Might be tricky to implement as core options, no? I believe I've never seen a core with the ability to set a path as a core option, but if that's possible then great, I agree these kind of things should be configurable from RA itself, not externally!

**Comment by twinaphex** [comment]
We'll likely have to figure something out. I will try to discuss with @jdgleaver what options we have.

**Comment by twinaphex** [comment]
Can I ask first what this 'starting dir' is used for?

**Comment by gingerbeardman** [comment]
`StartDir` in the `keropi/config` sets the initial path for the internal file selector menu/screen. 

I guess it could be set to the RetroArch ROM path?

**Comment by bslenul** [comment]
It's a setting to set the default directory when using the PX68k menu (either by pressing L2 or by starting the core without content), by default on Windows it defaults to C drive but the problem is that, AFAIK, there's absolutely no way to switch drive letter. So for example in my case my roms are in my F drive so the PX68k menu is pretty much useless now.

It's very useful for multi disks games, you can still use .m3u + the "Swap Disks on Drive" core option but for 3 or more disks games but it's a bit awkward IMO, especially for new users.

The removal of the `config` file also makes these 2 core options useless probably:

![image](https://user-images.githubusercontent.com/33353403/143437147-2ca6d084-de1e-4615-978e-a7328842dd05.png)

**Comment by gingerbeardman** [comment]
Good points.

I hope that Project IO can get this core back to a useful state, with as many options as possible/sensible migrating to RetroArch menu. 

This is my most used core so I am heavily invested in the outcome.

**Comment by twinaphex** [comment]
OK, after talking with @jdgleaver, while we search for a more standardized solution for this, in the meanwhile I guess I can bring back the external file loading so that people can still use the emulator in a mostly functional state.

**Comment by bslenul** [comment]
The "Save FDD/HDD Paths" core options would definitely need write access since it saves the paths in the `config` file. Although these options don't seem to work properly on Windows 🤔 

The `StartDir` thing is read-only however, so it should be fine for this one.

**Comment by twinaphex** [comment]
OK, I put it back -

https://github.com/libretro/px68k-libretro/commit/ebe9e166918ec30133b3c095c4c7eb5a97aafe99

let me know if it resolves the issues for you people.

**Comment by bslenul** [comment]
Hey, just tested that last commit on both Windows and my Linux VM, unfortunately that didn't work, it doesn't read `StartDir` and it doesn't write the FDD paths either.

**Comment by twinaphex** [comment]
I dunno then, I just backported what you said was the issue.

Here's another idea - you get this working and you send a PR. Failing that, you'll just have to accept this currently not working, it's best honestly not to have all this nasty file I/O going on - it's even using some Windows-specific API calls for this on Windows that I'd rather it's not using at all. It's a bad idea period in general to have this external config file reading, and it was the right call to remove it.

**Comment by twinaphex** [comment]
Fine, I've roleld it all back.

It should work now again.

I will have to redo all rebasing and cleanups I was doing and this time just not touch this precious 'external config file reading'. Honestly though, I want no more interferences after this. This entire codebase's upstream has not been active since 2014, the codebase is a disaster, it's chockful of Win32-isms, encoding issues, pointer arithetmic issues, and hard tough decisions need to be made to whip this core into something good. So you guys will have to understand from this point on why this entire codebase needs to be redesigned and re-engineered. We cannot have this codebase remain in this terrible condition, it really is right now plain and simply a bad core that reflects badly on Libretro/RetroArch, and it will need heavy alteration.

**Comment by gingerbeardman** [comment]
OK, agreed.

My issue was not that it should not be touched, but rather to understand the reasons for the removals (eg. removing the original Japanese comments is removing valuable information about the operation and logic of this emulator IMHO)
