### ISSUE TITLE
MIDI-out, instruments don't initialize properly

### ISSUE THREAD

**Issue by riggles1** [libretro/px68k-libretro#164]
Using Roland SCVA and MUNT everything turns into piano's as mentioned at the end of this bounty.
https://github.com/libretro/RetroArch/issues/6908

Instruments initialize properly with DOS and other things.
Adding it as an issue here as the MIDI feature is now implemented into the core, just not fully functional yet.

**Comment by riggles1** [comment]
@negativeExponent

We have an update on what may be causing this bug.

Nawell found the following info:

"When sending MIDI PC (program change) messages to set the instruments, the core sends two PC messages for each channel. The first one has the correct value, but the second one is a 00 value that defaults to a piano sound. That's the reason why all instruments ends up sounding like pianos. With MIDI-OX  you can log the core's MIDI output, and clearly see the issue."

https://cdn.discordapp.com/attachments/434713532341288961/1159953985235582976/px68k_midi_bug.PNG?ex=6532e654&is=65207154&hm=102e5379e8142dc0824138e4ed702d6d0a39e728b824973010b8923dbdf62ad4&

**Comment by biffrapper** [comment]
Sadly this has yet to be fixed even though this is a core breaking bug.

**Comment by negativeExponent** [comment]
@biffrapper add anything more useful than repeating the issue.

@riggles1 how can this be confirmed. i know that midi works with fluid.timity,munt through libretro api, though i dont have a comparison of how its suppose to sound on each setting, at least on my fork of px68k. i did notice a difference with using libretro api that it somehow add delay, or drop notes at the beginning when using timidity. and somehow if using fluidsynth directly in px68k lessens these said delays as well. as for sounding just pianos, dont think it does. i can only test through software midi(or whatever its called) under linux.

**Comment by riggles1** [comment]
@negativeExponent Not sure, both munt and roland va work perfectly for libretro dos. No idea why instruments aren't initialized properly here, all instruments seem to play well other than being only pianos. Win10 64bit.

**Comment by negativeExponent** [comment]
> @negativeExponent Not sure, both munt and roland va work perfectly for libretro dos. No idea why instruments aren't initialized properly here, all instruments seem to play well other than being only pianos. Win10 64bit.

it would be helpful if you can post sound samples. im not entirely sure of what is suppose to be the correct initialization. but i dont hear pianos here. unless im using munt (mt32) for example, and use Standard in libretro api's midi interface and use GS/GM/SC-55 device in game config  like Akumajou Dracula.

also helpful would be the synth used and its config its its other than default. i myself turn off reverb and echo in my settings coz its just annoying to listen sometimes.

thanks for the reply.

**Comment by negativeExponent** [comment]
MIDI_Reset never gets called until core close. Try adding MIDI_Reset() at the end of MIDI_Init() in x68k/midi.c

**Comment by biffrapper** [comment]
@negativeExponent   Yep I am on Windows 10 and have the same result on two different Windows machines.

**Comment by negativeExponent** [comment]
pushed a PR to fix this issue... at least as far as initializing instruments.

(tested with Nuke-SC55 + loopMIDI in a very very sloooow Windows 11 operating system.)

**Comment by negativeExponent** [comment]
after testing on a very slow windows machine, i can say as far as getting instruments initialized, it would appear that on the px68k side at least, the PR i sent, specifically only sending 3 bytes of data in midi_out_short_msg() should be enough to fix it. BUT, it appears that the winmm driver differs from the alsa driver in retroarch, to be specific, munt may still not correctly initialize instruments, but general midi and SC-55 sounded fine other than missing bend/pitch effects. This pitch/bend issue can be resolve by changing just one variable in winmm_midi.c.

i've look at dosbox, and despite it using the libretro api for midi, it appears to be just handling minimal commands, and the sysex buffer and handling is dont elsewhere

see: https://github.com/libretro/dosbox-core/blob/27b6dbe8608ff63aaf8d5b7257a2b08c7d1a7a90/src/gui/midi.cpp#L131

in any case, heres a modified px68k with the modification s for windows 64bit users. maybe RA just dont like my windows PC so this may work differently on other machines. send feedback if you can. tnx

[px68k_libretro_x86_64.zip](https://github.com/user-attachments/files/16233400/px68k_libretro_x86_64.zip)

**Comment by biffrapper** [comment]
Getting closer!  Had a few minutes to test and I noticed that the instruments were being held and not released, the longer the game ran.  I was playing Akumajou Dracula, fyi.  The pianos are gone and now instruments are initializing, but the pitch is sometimes off.

When I have some time later I'll post up a comparison video so you can hear.  I have a pretty powerful machine so has the horsepower to stream and upload.

Thank you so much for everything you have tried so far!

**Comment by negativeExponent** [comment]
thanks for the test and feedback. can you test with this modified version of retroarch? it should sound better for SC55/GM... but somehow MT-32 messages are still getting dropped somewhere.

heres the link: https://www.mediafire.com/file/d7mwx55oaw8nite/retroarch_x86-64_plus_dll.zip/file
github only limits 25MB for upload so i have to send this files from somewhere else. just to be on the safe side incase these (free upload site does nasty things), here is the hash of the actual zip.

```
retroarch_x86-64_plus_dll.zip	MD5	4BB3E3F7599C1EFFAE1F5BFD77AA5919
retroarch_x86-64_plus_dll.zip	SHA-1	0593DCF857CA1C3B57E724688965CEB695D5178E
retroarch_x86-64_plus_dll.zip	SHA-256	7B236EA3BF0C0CB4D71DEBB0F13377DADC297AA0258D2C7CF63CDA066A9F9449
retroarch_x86-64_plus_dll.zip	SHA-512	4021AEF0A26E3925C60D275C4D717E7A068180AE04C19188C8C82E0230352C81458415AA13F3EE7D58AE2FC5D2B57E4F44D04744C73A659BE7E629F945E2D01B

```

and here is the hash for the retroarch.exe only:
```
retroarch_x86-64_plus_dll.zip	MD5	4BB3E3F7599C1EFFAE1F5BFD77AA5919
retroarch_x86-64_plus_dll.zip	SHA-1	0593DCF857CA1C3B57E724688965CEB695D5178E
retroarch_x86-64_plus_dll.zip	SHA-256	7B236EA3BF0C0CB4D71DEBB0F13377DADC297AA0258D2C7CF63CDA066A9F9449
retroarch_x86-64_plus_dll.zip	SHA-512	4021AEF0A26E3925C60D275C4D717E7A068180AE04C19188C8C82E0230352C81458415AA13F3EE7D58AE2FC5D2B57E4F44D04744C73A659BE7E629F945E2D01B

```

you will need to run this on a separate retroarch folder though as the DLL will not be compatible with the release version. Just make a copy of your current RetroArch folder somewhere, delete the retroarch.cfg (so it will create new on with path for this testing folder) then just overwrite all files with the contents of the zip.

im not in hurry for your test result, so just take your time.

btw, what message can you see on your midi device? are you able to see for example 266 bytes long sysex messages? from F0 - F7? i can make a core post the midi msg on realtime and you can probably see and compare if what core is trying to send is actually recieved in your device. thanks.

lastly if you are to compile stuff, this would make things easier coz i can just post a repo of the changes and you compile. but i dont mid building it myself.

thanks.

**Comment by negativeExponent** [comment]
@riggles1 @biffrapper midi should be fixed now. you need to update both px68k and retroarch.
other individual PRs like no reset for midi type change has also been merged.

**Comment by biffrapper** [comment]
Thanks! I will test when I can, but unfortunately the latest version of Retroarch produces garbled graphics for some odd reason in vulkan.  Can't wait to try.

**Comment by negativeExponent** [comment]
thanks for the added info and tests. il helped narrow down most of the issue to be an RA windows driver problem.

**Comment by riggles1** [comment]
Woo, can't wait to get back home and give this a whirl :0 awesome!
