### ISSUE TITLE
m3u works only when it comes first in alphabetical order

### ISSUE THREAD

**Issue by ToniBC** [libretro/px68k-libretro#165]
When we load a zipped content, the order of priority should be, first if there are any .m3u files and then the rest, but it always loads the .dim files before the .m3u and multidisc doesn't work.

If you load it uncompressed, directly the m3u, there is no problem, it only happens when it is compressed.

Apparently the m3u is not the first thing to look at, rather the order seems to be last.

Thank you.

**Comment by gingerbeardman** [comment]
It is probably the order that they were zipped in, probably alphabetical from filesystem.

A workaround might be:
1. zip m3u
2. after that is finished add the disk images to the zip

If that works let me know.

The emulator should be able to cope, of course, but it's always good to find a workaround in the meantime.

**Comment by ToniBC** [comment]
Right, renaming the .m3u to be the first item in the zip does load it.

I guess the system does that, because it's easier than analyzing everything in the zip and establishing an order.

Interesting and it works smoothly, I didn't realize looking at that.

Thank you.

**Comment by gingerbeardman** [comment]
If you would be so kind to rename the issue, something like "m3u works only when it comes first in alphabetical order"

**Comment by ToniBC** [comment]
It works fine on compressed files, in the absence of confirmation that it is a matter of global Retroarch or the kernel, the file priority, the problem would be solved.

**Comment by negativeExponent** [comment]
Yeah you don't seem to understood but yeah whatever you think works to you against someone who worked on the core and some

**Comment by gingerbeardman** [comment]
@negativeExponent let's keep it friendly and civil

**Comment by negativeExponent** [comment]
the core itself do not handle roms in compressed format, so this issue is not valid here. there is no uncivil about that.

**Comment by gingerbeardman** [comment]
The uncivil was you trying to use your position as a contributor to belittle somebody else. There is no need. We're all friends. Correct or incorrect, beginner or experienced, it doesn't really matter in the grand scheme of things.

**Comment by negativeExponent** [comment]
Uncivil or whatnot (whatever you may think it is) it does not take away the point that the core is not intended to handle compressed formats, however you may want to arrange or rename the files in them. Don't try to stir the conversation into what it is not, like being 'uncivil' or whatever you folks may want to label it.

**Comment by gingerbeardman** [comment]
At this point you're arguing with yourself. Nobody said the core handles compressed files, only you. 

Rather it was simply stated that compressed files work, which is true.

**Comment by negativeExponent** [comment]
who cares

**Comment by ToniBC** [comment]
After some tests, something is wrong with the core with the compressed files.

For example, when we load an Amiga compressed file with the m3u and disks inside, the zip uncompresses to the Retroarch/saves/temp folder, but this core uncompresses it to user/your user/local/temp.

Although the route is different, which indicates that it is something of the core, otherwise the route would always be the same in all the cores. This does not always decompress all the content, only the .m3u, although others seem to.

If so, you could look at the code that the puae core uses when uploading a zip file and see what happens.
