### ISSUE TITLE
[BUG] Akumajou Dracula

### ISSUE THREAD

**Issue by rtomasa** [libretro/px68k-libretro#168]
As reported by other users, the first time you play the game you can go far with no issues. However, ever since that first play through, every time you get to the waterfall in level 2, when you whip the lion's head, the platform that you are standing on disappears.

This breaks the game. It only happens after you've already finished the stage and play the game again.

**Comment by Augusto7743** [comment]
Tested in core released in 2024-02-04.
That issue continue happening even if not finishing the second stage.

**Comment by rtomasa** [comment]
The issue does not happen if you change the core CPU speed to 16MHz

**Comment by Augusto7743** [comment]
An timing issue in core.
Thanks for sharing it.

**Comment by negativeExponent** [comment]
set to 25Mhz or higher cpu speed if the moving last line in status bar is annoying you.

**Comment by Kelvfimer** [comment]
I was testing latest changes from @negativeExponent and it seems the raft issue is gone. At least on my end, before if you had 100Mhz it vanishes and the only way to fix it was to set up the CPU Speed to 16Mhz. Now I tested with 100Mhz (OC) and RAM Size 12MB and the raft is there and no pitfall happens :). Pls can anybody test? thx

**Comment by negativeExponent** [comment]
It's not gone. It's there time to time unless mostly happening at low cpu speeds

**Comment by negativeExponent** [comment]
setting cpu clock to 16Mhz instead of default 10Mhz should remedy this issue.
