### ISSUE TITLE
Akumajou Dracula music issues

### ISSUE THREAD

**Issue by Augusto7743** [libretro/px68k-libretro#169]
Hello,
Thanks for reading my topic.

Start Akumajou Dracula.
In startup select the sound option 1.
In game title enter music options.
Select Music 6 Bloody Tears.
That music has issues in begin.

Compare with
https://www.youtube.com/watch?v=sRkRr-a2TQY
In time 26:06

Have an nice week.

**Comment by negativeExponent** [comment]
sounds fine to me. what exactly is the issue with it?

**Comment by negativeExponent** [comment]
since there is no update or details since, im assuming this as fixed (somehow)
