### ISSUE TITLE
Hellbound video glitches Boss 1

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/px68k-libretro#179]
Hello

Playing Hellbound with sc55 midi when reaching the first boss the screen glitches
![20240728_081242](https://github.com/user-attachments/assets/e51afc10-851b-4d3f-8bb3-46dcf75d6360)

Commit https://github.com/libretro/px68k-libretro/commit/c53afb993bb9338c297adf4182790b1da99116c0
Platform odroid n2+ retroarch 1.91.1 linux
I'm wondering @negativeExponent if you may know how to fix it.

Thx!!

**Comment by negativeExponent** [comment]
replace rom. the floppy variant appears broken to me but the HDD one works fine.

**Comment by Kelvfimer** [comment]
I'm using the hdf one that is a hard drive. Maybe is based on the floppies. Let me check.

**Comment by Kelvfimer** [comment]
I found a xdf that works :) thx again @negativeExponent

**Comment by gingerbeardman** [comment]
@Kelvfimer please post detail for future players

**Comment by Kelvfimer** [comment]
@gingerbeardman basically did what @negativeExponent told me. I look for other rom as the hdf one that I had, seemed to be corrupted. So I looked for a xdf rom and that worked.

**Comment by gingerbeardman** [comment]
Right, but you can let future people know the location that had the good disk or post the hash of the disk so people can find it more easily.

**Comment by Kelvfimer** [comment]
ah ok I found it in a forum and pointed to mediashare. However I see it is also in doperoms. The file Hellhound (1994)(Breakthrough).xdf has sha256 is 74F66291FE3F7AD2FAA072E7E53CD118105BFA769C9B6C8F21DAA4765B13B162

**Comment by gingerbeardman** [comment]
thanks!
