### ISSUE TITLE
Super Street fighter 2 or Hang On FM/PCM music degration

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/px68k-libretro#181]
Hello

Using internal music there are FM/PCM degration that can be very noticable at Hang On and after playing 10 minutes with Super treet Fighter 2  (Feilong or Cammy stages when changing to speed song before dying occurs always or when exotic animals screams at feilongs song)

it occurs in all commits but it's true latest commit https://github.com/libretro/px68k-libretro/pull/180 with Street Fighter occurs more frequently. 

I'm wondering @negativeExponent as you have knowledge concerning music boards per your commits, if you can pls take it a look. 

thx
KR

**Comment by negativeExponent** [comment]
Do not disable midi. It's a bud in cpu coz coz bus error handling not implemented

**Comment by Kelvfimer** [comment]
No worries. It could be great if you can fix it. If you need repro files let me know.

**Comment by negativeExponent** [comment]
in core options > advance, set everythin to Off, leave frame skip at full frames. the core was originally was on a specific frame phasing and all those other options were added later to remedy some timing issue especially sound. if your running higher than 10Mhz cpu clock, turn it back down.

**Comment by Kelvfimer** [comment]
Hello @negativeExponent it is as you said and the sound is even losing more using latest PR commit https://github.com/libretro/px68k-libretro/pull/180/commits/f6379a75cb1a49937f2a7a7ec12a2a0b13d40bef :( I'm using 10MHZ, RAM 12 MB, eveything off and full frame. How can debug it to provide you logs? thx

**Comment by negativeExponent** [comment]
see if anything changes in latest commit.

if it still sounds the same, make a recording and upload it. also, post a copy of retroarch.cfg and config/PX68K/PX68K.opt

**Comment by Kelvfimer** [comment]
thx for the binary @negativeExponent but I'm using Linux on an odroid n2+. not Windows with PC. 

Nevertheless, I've just tested on Windows downloading the latest core and on RA 19.1 and it is working fine... 

So I need to  troubleshoot a bit and I will provide a video :)

thx for your support and time.

**Comment by negativeExponent** [comment]
What do you mean MiDI OFf? From core options? 

You cannot run this core with MiDi off. As I've stated in the erased comment I've said on day one, the core do not have bus error handling which is suppose to switch to FM mode when Midi SW is off

**Comment by negativeExponent** [comment]
`[DEBUG] [Environ]: GET_VARIABLE: px68k_midi_output = "disabled"`

This can never be off as stated in the description. This bugs the core in it's current configuration.

**Comment by Kelvfimer** [comment]
@negativeExponent ok but even with px68k_midi_output = "enabled" it has those music glitches :) . Maybe it gets corrupted due to off and then on.

**Comment by negativeExponent** [comment]
Just leave MIDI core option to Off, even without a midi attached. Just use the in-game options to switch music mode to Mimi or internal(FM)

**Comment by Kelvfimer** [comment]
I was testing changing the audio driver and it doesn't matter if I use alsa alsathread or SDL2 it fails in the same way :( I change audio latency and the same.... I don't know what to do...

**Comment by negativeExponent** [comment]
Sorry meant to say leave MiDI option On. I should remove that option sine the code that's suppose to handle that has been removed.

**Comment by Kelvfimer** [comment]
thx @negativeExponent nothing worked I'm wondering if it's an issue on my flashed sd card...

BTW to compile with Musashi I had to remove 

ifeq ($(C68K),1)
FLAGS 			+= -DHAVE_C68K -DC68K_CONST_JUMP_TABLE
SOURCES_C 		+= \
				$(CORE_DIR)/m68000/c68k/c68k.c \
				$(CORE_DIR)/m68000/c68k/c68kexec.c

It doesn't matter what I did it was using DHAVEC68k.

I will reflash the sd card, I hope tomorrow and check if maybe is an issue anywhere in my Operating System. thx for your help and support.

**Comment by negativeExponent** [comment]
sad to hear that. issue probably is device specific or something is affecting core timings or whatever.

with regards to mushasi, it appears C68K is hardcoded to 1. you may need to run make C68K=0 to make it use musashi

**Comment by Kelvfimer** [comment]
Thx for all you help @negativeExponent . After reflashing a new sd card and having everything from the scrath in my OS the issue is gone even using the same disks (afaik the disk are preserving the data). 

I'm wondering that my previous SD had any issue with the OS. So the issue seemed to be external.
