### ISSUE TITLE
hatenkou does not start

### ISSUE THREAD

**Issue by mixerjdp** [libretro/px68k-libretro#196]
there is a problem with this rom 'hatenkou', mame version.  When i load with latest px68k it just keep showing a black screen.

**Comment by gingerbeardman** [comment]
Please post rom download source or hash so we can check with the same file.

**Comment by mixerjdp** [comment]
[INFO] RetroArch 1.9.4 (Git b1a3ea7)
[INFO] === Build =======================================
[INFO] CPU Model Name: 12th Gen Intel(R) Core(TM) i5-12400F
[INFO] Funcionalidades:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: May 31 2021
[INFO] Version: 1.9.4
[INFO] Git: b1a3ea7
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Versión de la API libretro: 1
[INFO] API usada en la compilación: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [SoftFilter]: Found plug: 2xBR (2xbr).
[INFO] [SoftFilter]: Found plug: 2xSaI (2xsai).
[INFO] [SoftFilter]: Found plug: Blargg NTSC SNES (blargg_ntsc_snes).
[INFO] [SoftFilter]: Found plug: Darken (darken).
[INFO] [SoftFilter]: Found plug: Dot Matrix 3x (dot_matrix_3x).
[INFO] [SoftFilter]: Found plug: Dot Matrix 4x (dot_matrix_4x).
[INFO] [SoftFilter]: Found plug: EPX (epx).
[INFO] [SoftFilter]: Found plug: Gameboy3x (gameboy3x).
[INFO] [SoftFilter]: Found plug: Gameboy4x (gameboy4x).
[INFO] [SoftFilter]: Found plug: Grid2x (grid2x).
[INFO] [SoftFilter]: Found plug: Grid3x (grid3x).
[INFO] [SoftFilter]: Found plug: LQ2x (lq2x).
[INFO] [SoftFilter]: Found plug: Normal2x (normal2x).
[INFO] [SoftFilter]: Found plug: Normal2x Height (normal2x_height).
[INFO] [SoftFilter]: Found plug: Normal2x Width (normal2x_width).
[INFO] [SoftFilter]: Found plug: Normal4x (normal4x).
[INFO] [SoftFilter]: Found plug: Phosphor2x (phosphor2x).
[INFO] [SoftFilter]: Found plug: Scale2x (scale2x).
[INFO] [SoftFilter]: Found plug: Scanline2x (scanline2x).
[INFO] [SoftFilter]: Found plug: Super2xSaI (super2xsai).
[INFO] [SoftFilter]: Found plug: SuperEagle (supereagle).
[INFO] [SoftFilter]: Found plug: Upscale1.5x (upscale_1_5x).
[INFO] [SoftFilter]: Found plug: Upscale_256x-320x240 (upscale_256x_320x240).
[INFO] Using 1 threads for softfilter.
[INFO] [Video]: Video @ 1680x1048
[INFO] [XInput]: Found XInput v1.4.
[WARN] [DINPUT]: Strong rumble unavailable.
[WARN] [DINPUT]: Weak rumble unavailable.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [D3D11]: Found GPU at index 0: Radeon RX 570 Series (CRT Emudriver)
[INFO] [D3D11]: Found GPU at index 1: Microsoft Basic Render Driver
[INFO] [D3D11]: Using GPU index 0.
[INFO] [Video]: Found display server: win32
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "d3d11".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [SRAM]: No se guardará la SRAM.
[INFO] [Playlist]: Cargando historial: [D:\Emulation\Emulators\RetroArch\content_history.lpl].
[INFO] [Playlist]: Cargando historial: [D:\Emulation\Emulators\RetroArch\content_music_history.lpl].
[INFO] [Playlist]: Cargando historial: [D:\Emulation\Emulators\RetroArch\content_video_history.lpl].
[INFO] [Playlist]: Cargando historial: [D:\Emulation\Emulators\RetroArch\content_image_history.lpl].
[INFO] [Playlist]: Cargando favoritos: [D:\Emulation\Emulators\RetroArch\content_favorites.lpl].
[INFO] [CONTENT LOAD]: Updating firmware status for: D:\Emulation\Emulators\RetroArch\cores\px68k_libretro.dll on D:\Emulation\Emulators\RetroArch\system
[INFO] [CORE]: Using content: D:\Emulation\ROMs\X68000\Hatenkou.m3u.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] RetroArch 1.9.4 (Git b1a3ea7)
[INFO] === Build =======================================
[INFO] CPU Model Name: 12th Gen Intel(R) Core(TM) i5-12400F
[INFO] Funcionalidades:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: May 31 2021
[INFO] Version: 1.9.4
[INFO] Git: b1a3ea7
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "D:\Emulation\Emulators\RetroArch\cores\px68k_libretro.dll"
[INFO] [Overrides]: Core-specific overrides found at "D:\Emulation\Emulators\RetroArch\config\PX68K\PX68K.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "D:\Emulation\Emulators\RetroArch\config\PX68K\X68000.cfg".
[INFO] [Overrides]: No game-specific overrides found at "D:\Emulation\Emulators\RetroArch\config\PX68K\Hatenkou.cfg".
[INFO] [Config]: Appending config "D:\Emulation\Emulators\RetroArch\config\PX68K\PX68K.cfg".

this is the rom file i use https://archive.org/download/MAME_0.202_Software_List_ROMs_merged/x68k_flop.zip/x68k_flop%2Fhatenkou.zip
it happens with all versions of rom file i have found.
im not an advanced user.  I've discovered that the ROM does work, but I have to load disc 1 first, wait 1 second for the operating system's boot screen to appear, and then load the second disc. If I load both discs at the same time or use an m3u file, the emulator will only display a black screen.

**Comment by gingerbeardman** [comment]
So i don't see a black screen, but rather an error screen generated by the contents of the disk.

- エラーが発生しました。リセットしてください。
- An error occurred. Please reset.

<img width="1312" alt="Screen shot 2024-09-24 at 23 10 22" src="https://github.com/user-attachments/assets/c07b25c5-ee6b-45e8-9fbf-5a1aaaf2665c">

So at this point I know it is not an emulator problem, but a user/support issue. Could be emulated computer system settings, or some other requirement of the game such as needing a user disk in drive B or something. 

So I looked inside the zip and there are two disks, so you need to insert them both (use F12 key once emulated system is running) and then reset the emulated system. Which gives you:

<img width="1312" alt="Screen shot 2024-09-24 at 23 15 17" src="https://github.com/user-attachments/assets/7498b437-db1a-466e-95e8-b10c0ac56581">

**Comment by negativeExponent** [comment]
set memory option to 4MB or higher.

**Comment by negativeExponent** [comment]
if the procedure is working. can we close this?

**Comment by mixerjdp** [comment]
The procedure was successful, I was able to run the game with those instructions, and the open issue can now be closed.
