### ISSUE TITLE
Super Street Fighter II - The New Challengers (Japan) there is A> popup on the screen.

### ISSUE THREAD

**Issue by Dunard** [libretro/px68k-libretro#199]
after loaded Super Street Fighter II - The New Challengers (Japan) (System Disk).dim + Super Street Fighter II - The New Challengers (Japan) (Disk 1).dim

Using this. Super Street Fighter II - The New Challengers (Japan).m3u

Even the Super Street Fighter II - The New Challengers (Japan) (System Disk).dim alone still showing the A>.

Do I need to type something in order get the next floppy to load?

I didn't had this issue on MAME x68000. But this didn't pop up on the px68k.

MAME

![Screenshot_20241223_231127](https://github.com/user-attachments/assets/0c89ab5e-3973-4329-982e-de746c4d57d7)

px68k

![IMG_20241223_231539108_HDR](https://github.com/user-attachments/assets/46e221c0-6cfe-4767-b5f7-5e8f3706e164)

**Comment by negativeExponent** [comment]
increase the ram option to 4MB or 8.

also, youll find it easier to play from na .HDF for multi-floppy types. or just mount each disk as necessary through the ingame UI (F12)

**Comment by Dunard** [comment]
Thank you. I set it to 12mb. It's working now. Loaded the Super Street Fighter II - The New Challengers (Japan).m3u and then loaded the rest up. Game loaded.

**Comment by negativeExponent** [comment]
very good. you may close the thread now if if you dont have any more related issue. thanks.
