### ISSUE TITLE
Android is not building

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/px68k-libretro#21]
It's not on the buidbot, I see no log there.

**Comment by retro-wertz** [comment]
its not yet on android's buildbot recipe

**Comment by r-type** [comment]
Hum honestly it's not really an core issue , it's an libretro-super issue.
if you build with make platform=android you will have an working android core .

You should open an issue on the libretro super and close this one.

**Comment by Tatsuya79** [comment]
Ok sorry, I wasn't sure.
