### ISSUE TITLE
Capcom games and linux issues

### ISSUE THREAD

**Issue by retro-wertz** [libretro/px68k-libretro#23]
Capcom games seems to have issues running under linux.

Street Fighter II and Super Street Fighter - both do not have FM audio working.
Final Fight - only drums/percussions are heard(using adpcm only?). missing the other fm channels
Daimakaimura (1994) - wont start at all, displaying an error message.
(not sure if there are other games affected as i only have limited roms atm)

my limited understanding and troubleshooting of the code led me to changing all instances of "pointer src;" to "u32 src;" from these files: 
c68k_op0.inc, c68k_op5.inc, c68k_op8.inc, c68k_op9.inc, c68k_opb.inc, c68k_opc.inc, c68k_opd.inc, c68k_ope.inc.
changing the one in c68k_op4.inc just causes segfault when it runs WRITE_WORD_F() so this file was ignored. the above change was enough to at least fix issues with the games but there must be something else needed, as there as some audio glitches like suddenly audio gets loud or audio sounding like a running a power amplifier with very low power input.
the use of "long" and related variables must have different effect running in windows than on linux. the D88 disk error issue(already fixed) was also been caused by the use of long variable instead of DWORD(unsigned int). 
im not sure how to code this properly as i lack the experience. hope this will help in troubleshooting the issue.

**Comment by r-type** [comment]
the original repo from hissorii/px68k was not support 64 bit, that why we back ported recent c68k from yabause . to support 64 bit.
I advice to not touch c68k stuff , typedef pointer is set from https://github.com/r-type/px68k-libretro/blob/master/m68000/c68k/core.h and should define correctly for your 64 arch.
```
#if defined(__LP64__)
// Generic 64-bit
typedef unsigned int u32;
typedef unsigned long u64;
typedef unsigned long pointer;
```
that said , as the core was design originally for 32 bit ,there must be somewhere in code that fault for FM (and maybe other thing like d88, on 64 bits system.

**Comment by retro-wertz** [comment]
i already did change typedef pointer to something with 4 bytes size to (since long in windows is 4 bytes and long in linux is 8 bytes) but there is a lot that uses the "pointer" that just causes segfault.  that led me to just isolate areas that uses that.  

the same problems in linux can be replicated in windows if we change typedef pointer to typedef unsigned long long or uintptr_t(which sizeof is 8 bytes) or any that is not 4 bytes variable.

**Comment by r-type** [comment]
As said previously you must fix it outside the c68k core. I will not merge
change in c68k core .I prefere having no fm than bad hack.

Le 6 juin 2017 00:53, "retro-wertz" <notifications@github.com> a écrit :
>
> i already did change typedef pointer to something with 4 bytes size to
(since long in windows is 4 bytes and long in linux is 8 bytes) but there
is a lot that uses the "pointer" that just causes segfault. that led me to
just isolate areas that uses that.
>
> the same problems in linux can be replicated in windows if we change
typedef pointer to typedef unsigned long long or uintptr_t(which sizeof is
8 bytes) or any that is not 4 bytes variable.

**Comment by retro-wertz** [comment]
regenerating cpu from latest c68k source from yabause fixes linux issues.
https://github.com/Yabause/yabause/tree/master/yabause/src/c68k

**Comment by r-type** [comment]
did it works outwith change with hellhound or we have to reapply the fix ?

**Comment by retro-wertz** [comment]
reapply hellhound patch.

**Comment by r-type** [comment]
ok I update to the last c68k core like you suggested.

**Comment by zoharxero** [comment]
Seems to fix fm for mac too, only tested sf II.

**Comment by retro-wertz** [comment]
this should be working now. thanks alot @r-type
