### ISSUE TITLE
[Android] Crash when trying to insert disk

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/px68k-libretro#25]
In the Switch GUI (retropad L2), trying to insert a disk causes a crash of Retroarch.
Path finding seems to cause problem.

Android 4.1.2 Galaxy S3

**Comment by retro-wertz** [comment]
cleanup path from keropi/config

**Comment by Tatsuya79** [comment]
Oh yes thanks, stupid mistake.
And I had to change that "storage" to "mnt" on this phone too.
Works fine now. :)
