### ISSUE TITLE
Disk in fdd1 can block loading (upstream bug)

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/px68k-libretro#31]
Example with Granada.
Inserting disk1 only in fdd0, the game launches fine.
Inserting disk1 in fdd0 and disk2 in fdd1, black screen, stuck there.

This happens in stand-alone px68k on android too but winx68k doesn't have that issue at all in windows.
Would be interesting to know what made that happening.

**Comment by retro-wertz** [comment]
thought this was normal. found a bunch that wont run when both fdd are
occupied.

**Comment by Tatsuya79** [comment]
XM6 Type G get stuck on disk 2 too, so I don't know any more!

**Comment by negativeExponent** [comment]
boot override. dunno how other standalone emu are doing these but they probably override boot sequence depending on which drives are occupied or whatever.

by default core boots from RAM if populated. manipulating sram $ed0018 to boot from FDD instead and on a specific drive (drive A mostly for boot disks) disabled searching for disk in fdd1 (causing game to not boot at all)

**Comment by negativeExponent** [comment]
@Tatsuya79 lemme know if the option "px68k_save_fdd_path" will satisfy this requirement. or is there really a need to have a floppy inserted and hdd0 drive attached and yet boot on the HDD by default.

**Comment by Tatsuya79** [comment]
Indeed it's working fine in px68k now even if I insert both disks right after boot.

I tried xm6 type-G again to see and it's still stuck until I eject disk 2.

Guess I can close this issue, thanks.

**Comment by negativeExponent** [comment]
wierd that this happens on xm6 as well. 

anyways the game is suppose to boot with only Disk1 in the drive. after disk1 is finished with its intro it will then ask for disk2 on fdd1 and disk3 on fdd0. i think the game itself, sometimes, will be unable to show the "insert disks prompt" when a disk is already loaded in fdd1, its probably expecting it to be empty. but this is just guessing at this point.
