### ISSUE TITLE
In game disc changing crashes on andriod

### ISSUE THREAD

**Issue by KristopherTadlock** [libretro/px68k-libretro#41]
In game, pressing the left shoulder button brings up the system menu. Navigating to the disc drive, then pressing "A" should bring up a file dialogue to select the next disc. This works fine on windows. This causes and immediate crash on andriod. Running andriod version 4.4 and RA 1.6.7, using an RK3288 chipset on a GPD XD device.

**Comment by retro-wertz** [comment]
delete < system> /keropi/config as this is pointing to an invalid location.

**Comment by retro-wertz** [comment]
if StartDir is invalid, core will crash when trying to change and browse for fdd/hdd to use.
PR forces a fallback to use the current rom path to remedy this, this would also make it easier to load more disks if they are on the same folder.

its still prefered to specify StartDir= to the correct x68000 rom path e.g. /home/x68000/roms/
http://docs.libretro.com/library/px68k/

**Comment by negativeExponent** [comment]
i cant replicate this. even an invalid StartDir does now cause any crash
