### ISSUE TITLE
No controls work after latest updates

### ISSUE THREAD

**Issue by msheehan79** [libretro/px68k-libretro#45]
Hello, I updated from source today and now the core won't respond to any joystick or keyboard commands other than F12 (Enter the px68k menu). Also updated RetroArch from source so both are current builds.

I had just installed px68k earlier this week and had working controls, so this appears directly related to one of the commits done in the past day or so. 

Also noticed the Controllers options in the Quick Options section of RGUI is now gone, not sure if this was by design or is part of the issue.

Also to add this is on an RPI3 running RetroPie. I also have a keyboard connected w/ USB, and again the only keypress that seems to do anything is F12.

**Comment by retro-wertz** [comment]
interesting, i just had tested this on latest commits of retroarch and
px68k and it works fine. try to go to quick menu, controller and reselect
your gamepad. if it works this way, then you still have an older retroarch
which had this issue. this was just fixed a few hours ago..

if you have or use any controller remaps, then just re-save the remaps.

**Comment by msheehan79** [comment]
That is my issue, when I go to "Quick Menu", there is no Controller option anymore. Was there yesterday. Let me wipe out my RetroArch configs to see if it shows up again. Thanks for the quick reply!

**Comment by retro-wertz** [comment]
what system/platform you using?

**Comment by msheehan79** [comment]
Raspbian Jessie/RetroPie on RPI3. Also updated RetroArch from source about an hour ago just in case it was related.

**Comment by retro-wertz** [comment]
hmm im able to see controls using rgui, not sure rpi3 though as there are stuff disappearing in rgui, hence i dont use it.

**Comment by msheehan79** [comment]
After a little bit of testing, I have figured out how to reproduce the issue. 

When the core first launches the Controllers option is not present in Quick Options. If I go to Settings/Input/User 1 Key Bindings and change the controller type there, after that the Controllers option reappears in the Quick Options menu and input works normally again. 

The same issue is also present in lr-bluemsx so I'll open an issue there as well so anyone else who runs into this can at least work around it until a proper solution is available.

**Comment by fr500** [comment]
In the latest RetroArch this has all been addressed.
It will always show controllers, show the descriptors, etc.

It's just a matter of updating RetroArch

**Comment by msheehan79** [comment]
Thanks for your help, it was due to an out of date version of RetroArch. 

For future reference updating RetroArch from source within the RetroPie-Setup script does not get the absolute latest commit, so good to be aware of this. Looking forward to trying out the keymapper once I get RA updated.
