### ISSUE TITLE
[Enhancement] Some sort of repeat-keys when using the menu.

### ISSUE THREAD

**Issue by ghost** [libretro/px68k-libretro#46]
To be able to hold UP or DOWN when browsing the menu and your file lists would be helpful. as of the moment you move up or down one-at-a time, would be tedious to keep pressing the buttons when browsing 1.7k worth of game titles.

I made something similar like a turbo function inside Joystick_Update() which does repeat down and up for keyboard/gamepad but im sure there is a better way to have the feature

https://hastebin.com/bewinoluxe.diff

**Comment by gingerbeardman** [comment]
Yes! Maybe left/right can jump a page at a time.

**Comment by gingerbeardman** [comment]
I'm implementing some QOL improvements to this core and this is one of them, including left/right to jump a bunch at a time (like the RetroArch menu does). Will push this week.

**Comment by negativeExponent** [comment]
this is implemented now in latest commit, so this can be closed.
