### ISSUE TITLE
Input keymaps no longer working

### ISSUE THREAD

**Issue by cmcginty** [libretro/px68k-libretro#53]
I can load games using the core, but I can't any inputs to work. Is there additional setup needed? I saw a report about new input method is conflicting with the core? What input type to use (keyboard or gamepad)? Should "Analog to digital Type" be enabled for an analog stick? Any help would be appreciated. Thanks.

**Comment by twinaphex** [comment]
I think @fr500 would probably know most about this.

**Comment by fr500** [comment]
It's working fine here.
Set device to keyboard, back out of controls and go back in and there you can set your keys to gamepad bindings

@twinaphex when the device is changed the menu should be refreshed automatically. I can't figure how to do that.

**Comment by msheehan79** [comment]
Also make sure you aren't using an older build of RetroArch - I think the first major release where the keymapper was implemented was 1.6.8 so if you have 1.6.7 or earlier this core will have no input until you update RetroArch.

**Comment by twinaphex** [comment]
@fr500 Alright, noted - we can try to put that on the agenda for this upcoming release. Might require some testing between you and me though.

**Comment by cmcginty** [comment]
@fr500 Here's the default setup when I select gamepad:


![img_20180102_214532](https://user-images.githubusercontent.com/277249/34510228-db5f5850-f006-11e7-85fd-17e9d881efee.jpg)

When I switch to keyboard, I can't navigate the builtin px68k menu anymore:

![img_20180102_214555](https://user-images.githubusercontent.com/277249/34510213-c083c3fe-f006-11e7-8e4c-4fb4c3fb43ec.jpg)

So the default keymaps are not initialized, what are the normal values? I'm testing the Gradius and this is what I get after it loads, but like I said I can't move the mouse or anything from this screen.

![img_20180102_214310](https://user-images.githubusercontent.com/277249/34510243-0c6207a4-f007-11e7-8a96-0310e23c6245.jpg)

**Comment by cmcginty** [comment]
I also tried using keyboard and mapping dpad to up/down/left/right arrow. After that, i still can't navigate in the internal p68k menu. And also does not provide any way to move the mouse cursor. I also tried mapping tab key to a button, also does not do anything.

**Comment by retro-wertz** [comment]
that screen in gradius can only be navigated if Joy/Mouse in PX68K Menu is set to Mouse, then use the mouse to navigate the ingame pointer.

**Comment by cmcginty** [comment]
I set to mouse in the menu and then reset the game. My mouse works in retroarch, but does not register in the game. When using the mouse does it matter what the user1 and user2 inputs are set to?

**Comment by retro-wertz** [comment]
the pointer should still move regardless of the setting of user1 user2
input. on what device/system are you playing? you do have a controller
right?

**Comment by cmcginty** [comment]
Ah, ok I Ghouls n' Ghosts and was able to get the controller working! I'm still stuck however with the mouse in gradius. I have a PS4 controller and USB mouse/keyboard hooked up.

**Comment by msheehan79** [comment]
Just FYI, there is another dump of Gradius out there that boots directly into the game and doesn't require mouse input.
