### ISSUE TITLE
Core crashes if you try to browse directory it can not read

### ISSUE THREAD

**Issue by cmcginty** [libretro/px68k-libretro#54]
When selecting disks in the PX86K menu, if I try to browse /root the core crashes. I assume this is because I don't have read permissions on that directory.

**Comment by retro-wertz** [comment]
edit px68k config file (in system/keropi/config) and edit out StartDir= to one that exists for your device and end it with / or \ depending on which your filesystem supports.

**Comment by cmcginty** [comment]
The start dir is currently `/` which works fine. When I go to `/root` is when it crashes.

**Comment by negativeExponent** [comment]
my current testing on arch, browsing to /root only restores your pointer to the top, it does not crash so probably somewhere along the way this has been already fixed.

**Comment by gingerbeardman** [comment]
@negativeExponent you forgot to close

**Comment by negativeExponent** [comment]
opps! im not used to my new powers yet...
