### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Exalm** [libretro/px68k-libretro#57]
Where is px68k license specified? :)

**Comment by gingerbeardman** [comment]
See here: https://github.com/libretro/px68k-libretro/blob/master/doc/kero_src.txt

You can reach out to the original author for clarification, contact details at: https://github.com/hissorii/px68k

Section 4, machine translation:

> ---------------
> 4. Secondary use, distribution conditions, etc.
> ---------------
> 
> As long as you do not use quotient, except for some files, you are free to modify, breath free
> is. There is no obligation to publish the source code concerning software made by Park.
> It is unnecessary to contact (although I used it - I'm happy (laugh)).
> 
> Out of the above conditions,
> 
>   1. MPU Core
>      It is a work of Mr. Mike Coates and Darren Olafson. When diverting, both
>    Please contact and get permission to use.
> 
>          Mr. Mike Coates Contact: mcoates@mame.freeserve.co.uk
>          Darren Olafson Contact: deo@mail.island.net
> 
>   2. WINDRV.C
>      It is the work of Mr. yamama. When diverting, contact Mr. yamama and get permission to use
>    Please.
> 
>          Mr. yamama Contact: yamama@ps.ksky.ne.jp
> 
> Then, for OPM.C, variable names and functions are somewhat different, but basically
> Is based on Mr. Jarek Burczynski's code, so please be aware of that point
> I would be pleased.
> 
> In the case of distributing this code itself, without changing the contents of the archive,
> Please distribute it in one set.
> 
> I will not give up on copyright (even if I want to do it in the country, I can not do it). But,
> Please use it as you like (laugh).
