### ISSUE TITLE
[Enhancement] Support for Rewind

### ISSUE THREAD

**Issue by Darknior** [libretro/px68k-libretro#60]
Hi
Is it possible to have the rewind option ?
I don't know if it's possible, i know it's not on some systems because it use so many memory or proc ... but i think it's possible on PI3.

**Comment by gingerbeardman** [comment]
I'll look into this. Not sure at the moment how feasible it is. I'm hopeful.

**Comment by Darknior** [comment]
Hi :)
Some news about this one ?
I know it's not an easy feature but really cool to help on some trick games ...

**Comment by gingerbeardman** [comment]
As I understand it, Save Sates will need to be done before this can be.

**Comment by Darknior** [comment]
Ok i understand, it's what i've guess too ;)

**Comment by negativeExponent** [comment]
Savestate support has been added, which in return supports rewind.
