### ISSUE TITLE
[Enhancement] Support for Fast forward

### ISSUE THREAD

**Issue by Darknior** [libretro/px68k-libretro#61]
Hi
Is it possible to have the Fast forward option ? It's really cool to skip animations and so long loading ...
Thanks

**Comment by gingerbeardman** [comment]
I'll look into this. 

It should be possible to at least hook Fast Forward into the "NoWait" (unthrottled) option on the emulator F12 menu.

**Comment by Darknior** [comment]
Ok cool :)
But i think to have it link to the LR menu, to assign hotkeys to it.
When we play we press SELECT+R1 to accelerate the game.

**Comment by gingerbeardman** [comment]
Yes, agreed 👍

**Comment by Darknior** [comment]
Some news about this feature ?
Because now when i try it it works !!
The only problem was on Dracula for exemple SELECT make PAUSE GAME lol
Not really easy to use this key has HOTKEY :p
But if i'm right we can close this issue.

**Comment by gingerbeardman** [comment]
I guess the new CPU core unlocked this feature!?

**Comment by LibretroAdmin** [comment]
No idea, there hasn't been a response to this issue in over two years and it got reported that it could be closed. If anyone could check up on this and actually verify if it is fixed or not, we could proceed.
