### ISSUE TITLE
[Enhancement] Add PX68K options to RA core options menu (for saving game overrides)

### ISSUE THREAD

**Issue by Darknior** [libretro/px68k-libretro#62]
Hi
I think it is really a good idea and the best way when we use an RA emulator, to put all specific system options on his CORE options menu. Like they already do for SNES, Arcade, etc ...
But i know that MAME avec some options like CHEAT in an other internal menu.

I know it's really complicated because it is small, there is not many place, but maybe put there the most important options that we use to configure specific games to work.
Like that we can save core options by games like on other systems to make them working fine and launch them easily each time we want to play.
And give also us a way to share games configuration.

The other way possible is to create a database like on the last Amiberry!
It's a fantastic idea and they configure many games from many years to make them all working fine for every one. But the problem was the games are identified by archive SHA1 or NAME.
On AMIGA it's possible because every one use same games coming from an unique repo where they share a full set. And it don't exist on X68000.
They have plan now to add online update to update database, and also upgrade it with new games settings. A beautiful project :)

**Comment by Darknior** [comment]
Exemple of my GB general core option : 
I can modify it for each games, it is one of the RA emulation power :)

```
gambatte_gb_bootloader = "enabled"
gambatte_gb_colorization = "internal"
gambatte_gb_internal_palette = "Special 1"
gambatte_gbc_color_correction = "disabled"
gambatte_gb_hwmode = "GB"
gambatte_gb_link_mode = "Not Connected"
gambatte_gb_link_network_port = "56400"
gambatte_gb_link_network_server_ip_octet1 = "0"
gambatte_gb_link_network_server_ip_octet2 = "0"
gambatte_gb_link_network_server_ip_octet3 = "0"
gambatte_gb_link_network_server_ip_octet4 = "0"
mgba_solar_sensor_level = "0"
mgba_allow_opposing_directions = "OFF"
mgba_use_bios = "ON"
mgba_skip_bios = "OFF"
mgba_idle_optimization = "Remove Known"
```

**Comment by Darknior** [comment]
Amiberry XML database exemple : 
Easier to share because only one file, but not really in the spirit of RA emulators.

```
	<game filename="1000Miglia_v1.2"  sha1="2a82b5f47c00de451ea14ca9fe82880a79c08a7f">
		<name>1000 Miglia</name>
		<slave_count>1</slave_count>
		<slave_default>1000Miglia.Slave</slave_default>
		<hardware>
PRIMARY_CONTROL=JOYSTICK
PORT0=JOY
PORT1=JOY
		</hardware>
		<custom_controls>

		</custom_controls>
	</game>
	<game filename="1869_v1.2"  sha1="d46efad47f75ab570cf2f6a99fa8a82b9815c386">
		<name>1869</name>
		<slave_count>1</slave_count>
		<slave_default>1869.Slave</slave_default>
		<hardware>
PRIMARY_CONTROL=MOUSE
PORT0=MOUSE
PORT1=JOY
SCREEN_HEIGHT=200
SCREEN_Y_OFFSET=3
		</hardware>
		<custom_controls>

		</custom_controls>
	</game>
```

**Comment by negativeExponent** [comment]
this is now implemented on latest commit, so this can be closed.
