### ISSUE TITLE
1 frame of input lag that could be removed

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/px68k-libretro#72]
Comparing with MAME this core has an extra frame of input lag that could be removed.

**Comment by retro-wertz** [comment]
did these awhile back (think its on the forums still)

move these before the start of main loop in WinX68k_Exec
https://github.com/libretro/px68k-libretro/blob/master/libretro/winx68k.cpp#L542

or better yet move it entirely before WinX68k_Exec. I also have a closed-uncommited PR in pull request that fixes the ram and input cleanup if your interested in applying it.

**Comment by Tatsuya79** [comment]
Great that's working! Awesome. :+1: 

Any other fix is welcome, I'm not sure what are the issues you're mentioning exactly.

**Comment by retro-wertz** [comment]
https://github.com/libretro/px68k-libretro/pull/66

**Comment by Tatsuya79** [comment]
Ok, all that got merged. Thanks.
https://github.com/libretro/px68k-libretro/pull/75
