### ISSUE TITLE
Manjaro installation issue

### ISSUE THREAD

**Issue by demic78** [libretro/px68k-libretro#76]
Hi, I cant install px68k-libretro from AUR. Is it a known issue? Some suggestion? I receive this error during compilation:
collect2: error: ld returned 1 exit status
make: *** [Makefile.libretro:323: px68k_libretro.so] Error 1

Thanks for your attention!
Bye
Davide

**Comment by gingerbeardman** [comment]
What method are you using to build?

**Comment by demic78** [comment]
git clone+make, yay, makepkg, pamac... the others libretro cores installed without issues. Only this core seems to be the problem.

**Comment by gingerbeardman** [comment]
Googling the error gives this
https://stackoverflow.com/questions/26993701/collect2-error-ld-returned-1-exit-status

**Comment by demic78** [comment]
Ok, so have you an idea about what I can do to fix this issue? What can I modify in source files to fix the error? Really, I'm a newbie.. your googling seems to me a bit hard to understand... Thank you!

**Comment by demic78** [comment]
Ok... after Manjaro system updates the installation finally works!

**Comment by gingerbeardman** [comment]
congrats!

**Comment by negativeExponent** [comment]
seems like everything is ok now. congrats.
