### ISSUE TITLE
[macOS] core broken: from 1.7.3 onwards

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/px68k-libretro#80]
Trying to figure out when this started by going back through versions.

This is with 1.7.5 stable standard graphics build.

![screen shot 2019-02-07 at 15 30 30](https://user-images.githubusercontent.com/49612/52424189-60bd1480-2af1-11e9-8d69-7d8c314113e8.png)

**Comment by gingerbeardman** [comment]
OK, so:

(stable versions)
1.7.2 - works
1.7.3 - does not work
1.7.5 - does not work
1.7.6 - does not work

Exact screen colour/black/mess varies by game.

**Comment by gingerbeardman** [comment]
Seems OK in 1.7.8 on Mojave

**Comment by negativeExponent** [comment]
nice. the core can live on forward :D

**Comment by negativeExponent** [comment]
you seem to be referencing a retroarch version. core does not have anything to do with what version RA is. in anycase, i dont have mac/ios so you have to give more info/troubleshooting details than just saying "not working". a bisect probably if its indeed something or RA (as you are refering to RA version), or core.

**Comment by gingerbeardman** [comment]
I was under the (mistaken?) impression that old 六百間 versions pulls down cores of similar age? If this is not the case I will need instructions how to bisect the core rather than the RetroArch main app.

Also, I did say more than "not working" in that I described the black screen and showed a log of how far through things got, and what happened when I interacted with the emu.

But I'm happy to do some testing on whatever way is useful. Cheers!

**Comment by gingerbeardman** [comment]
Let me know if this thread or #32 is better

**Comment by gingerbeardman** [comment]
Hmm, maybe I am missing something...

I restored a backup of RetroArch.app and cores from Aug/Sep 2019 (PX68K core 85d59f0) just after I last confirmed it working and it now gives me the same black screen. Will do some more testing.

Am I losing my mind? 😜
