### ISSUE TITLE
The Dracule DIM game working fine, HDF one is very slow

### ISSUE THREAD

**Issue by Darknior** [libretro/px68k-libretro#93]
Hi

I've try to play this game with an working HDK image tested from many years on xbox 1, with my PI3 and it is very slow ... impossible to load the game.
I try the same game in DIM format and it works like a charm...

Same with an other ***(Hard Drive).hdf game.

Is it a bug ?
Or is there a solution ?
Thanks

**Comment by negativeExponent** [comment]
make it clear. is the game running but slow? or not loading at all. I dunno what Dracule game is, but used mostly HDF and most commercial games works fine, including Dracule (assuming you meant Akumajou Dracula) but im on PC...

**Comment by Darknior** [comment]
The game is running in DIM and HDF but in HDF it is really slow. I can't never see it starting :(
On Xbox 1 a 700 Mhz proc with 64 Mo of RAM it run fastest than the DIM file and it's why we use HDF games to skip loading time.
I will make more test this evening ... with Akumajou Dracula.

**Comment by gingerbeardman** [comment]
Do it does not load?

How far does it get? Please post debug video.

**Comment by Darknior** [comment]
@gingerbeardman i will make it this evening ;)

**Comment by Darknior** [comment]
I have try an other game : 
undeadline Genjuuki (Japan) (Hard Drive)

1 min 34 to come to the game first logo.
After it works perfectly, but all the loadings are very very long ... near 1 minute from the logo to the title screen when i press a key :(

For : Akumajou Dracula (Japan) (Hard Drive) 

About 1 min to come to this screen : 

1. x68000 Sound
2. MT-32 CM-32 CM 64 Sound
3. SC-55 SC- 33 CM-300 CM-500 Sound

The only one working for sound is the choice : 1
I choose it and i must stand for minutes more.

I become to hear some cracling sound after 3 min 40 but always black screen :(
After 6 min always black screen i stop it.

If i try the floppy 2 discs version i can see the title screen after only 25 sec.
It's strange because on xbox they made these hard drive games version to make them loading faster.

Maybe it's only a PI3 issue ?

**Comment by Darknior** [comment]
Finally after 10 minutes of crackling sound Dracula is running at full speed.
It's cool because with hard drive version i can see some game save :p 
I launch one save and the game is working fine, full speed and no bug.
The problem is during the first loading all all the game, it take an eternity and i don't understand why ?
Thanks

**Comment by negativeExponent** [comment]
1 min loading time, even on 10 Mhz clock speed is not right at all.

**Comment by Darknior** [comment]
No i'm not a 10 Mhz it s so long, i'm use a little overcked proc at 66Mhz and 8 Mo of RAM.
But i know it can make some bugs :(

Why not adding an option like on C64 to make loading fastest ?
Or like on NeoGeo they detect Loadings to skip them, it is really cool for a modern player.
They let the user choose, real emulation or upgraded emulation, because some time it can cause some bugs.

**Comment by negativeExponent** [comment]
hi. if this is still a problem for you, can you test with latest core and retroarch available for the device you use it on?

**Comment by Darknior** [comment]
@negativeExponent thanks a lot now it load really fast on PI, only 10 sec to load the game :)
**x68000 Sound** is always working fine, but MT-32 CM-32 CM 64 Sound and **SC-55 SC- 33 CM-300 CM-500 Sound** are always not supported.
Or maybe i must do something to make them work ? Like use a MIDI sound library some where for MT32 ?
Thanks

**Comment by negativeExponent** [comment]
expansion audio/midi has not been implemented. i dont think it is even implemented yet in the original hiiroki px68k.

**Comment by Darknior** [comment]
Yes thanks a lot i close it :)

**Comment by gingerbeardman** [comment]
Thanks for checking this @Darknior !
