### ISSUE TITLE
Core broken on linux and windows (and others?) [Retroarch 1.7.8]

### ISSUE THREAD

**Issue by paradadf** [libretro/px68k-libretro#94]
Hi! After installing Retroarch 1.7.8 the core stopped working. I've tested it on Windows and Linux. Bios are inside the keropi folder, right checksum and tested roms worked before.

**Comment by gingerbeardman** [comment]
Stop working how?

I do not have much time to test but I see this on macOS:

![Screen shot 2019-09-03 at 22 31 11](https://user-images.githubusercontent.com/49612/64210207-9022dc80-ce9a-11e9-8882-45a62fc7d7ae.png)

**Comment by paradadf** [comment]
I can only show you the log I get... I don't know why it doesn't work
https://pastebin.com/yX1wcMfS

**Comment by negativeExponent** [comment]
how does it not work? what is actually happening? does the core launch at all? does the core stops at black screen? can you open the menu (F12)? do you have any other fdd/hdd images to test?

**Comment by paradadf** [comment]
The core doesn't launch at all. I've tested dim and hdf files. But If you @negativeExponent are using 1.7.8 and it works, then I might just make a complete reinstall.

**Comment by negativeExponent** [comment]
im on latest commit everythin on linux. try running px68k without content (using Load Core only) see if menu at least appears.

**Comment by paradadf** [comment]
Hi! This is what I get:
<img width="406" alt="px68k retroarch" src="https://user-images.githubusercontent.com/15956550/64267187-eb3ce980-cf03-11e9-8d2f-cb84647cbaaa.png">

**Comment by gingerbeardman** [comment]
I would try a new install.

**Comment by negativeExponent** [comment]
i dont think that is even related to the core. loading it might have triggered that error but it sure is not the core itself since it does not have cdrom core in it

**Comment by paradadf** [comment]
That‘s why I think it might be Retroarch 1.7.8 conflicting somehow. The thing is, I get that CDROM stuff on my Raspberry Pi too. Anyway, I‘ll make a clean reinstall and hope for the best. Many thanks for the help!

**Comment by paradadf** [comment]
I can finally tell what's going on! px68k crashes/doesn't boot if `video_threaded = true` in retroarch.cfg. That didn't happen before.

**Comment by negativeExponent** [comment]
ok this can be closed then...
