### ISSUE TITLE
Sound choking in games like Chourensha 68K and Akumajou [Ubuntu 18.04]

### ISSUE THREAD

**Issue by emersonnovais** [libretro/px68k-libretro#96]
Games like Chourensa 68K and Akumajou Dracula worked very well few months ago and now they have some choking and the sound not works like before. It's a problem with my configuration or with the sound? I noted this issue with the last version, 1.8.2.

My system: 
Ubuntu 18.04 64bits
Core i5 M460
GPU: Nvidia 310M

Thanks. 

[edit]
I noted when the shot button is keypressed the choking started. In Chourensha, if none shot is pressed the sound works normally.

**Comment by gingerbeardman** [comment]
Do you have Turbo button setting activated in RetroArch?

**Comment by emersonnovais** [comment]
Previoslly, the sound worked with or not turbo button. Other thing that I noted is if a bomb or other sound event if explode in the game the sound works normally with a few seconds and choking again when the button is pressed.

**Comment by negativeExponent** [comment]
i doubt its caused by the core, since it hasn't been updated in months. And i have just tested the core a few hours ago (testing playlist log) without having any problems.

**Comment by emersonnovais** [comment]
Recetly I updated the GCC version because MAME isn't works. This may cause the problem?

**Comment by negativeExponent** [comment]
> Recetly I updated the GCC version because MAME isn't works. This may cause the problem?

this does not explain anything as to why i would have been an issue.

**Comment by emersonnovais** [comment]
This is bizarre to me. See the video that I recorded about the bug. I use an generic speaker with my notebook. If the sound is this out speaker, the bug appears. When I disconnect and use the embbed speaker of the notebook, the bug disappears. I tested the speaker following if it had a problem with them but the speakers are ok. I checked until if the speaker P2 conector had a short but it is ok too. If I connect my Galaxy headphone in the bug appears again. I tested other games with the other cores like MAME, Genesis Plus GX and SNES9x and not show this bug. See the video bellow.

[https://youtu.be/rUXyPFqjWCg](url)

**Comment by gingerbeardman** [comment]
I think your computer has a problem.

**Comment by negativeExponent** [comment]
> This is bizarre to me. See the video that I recorded about the bug. I use an generic speaker with my notebook. If the sound is this out speaker, the bug appears. When I disconnect and use the embbed speaker of the notebook, the bug disappears. I tested the speaker following if it had a problem with them but the speakers are ok. I checked until if the speaker P2 conector had a shortcut but it is ok too. If I connect my Galaxy headphone in the notebook the bug appears again. I tested other games with the other cores like MAME, Genesis Plus GX and SNES9x and not show this bug. See the video bellow.
> 
> [https://youtu.be/rUXyPFqjWCg](url)

can you edit the YT link? its not clickable.

anyways can you try to turn No-WaitMode to ON from the px68l menu? (F12) and see if this does anything (not that it would...).

**Comment by emersonnovais** [comment]
Done.

**Comment by emersonnovais** [comment]
Solved. I tried various configuration with drivers and none of them worked. I reenabled the mic output in the Ubuntu Settings and works. Sorry for both you about the bug. I will close the issue now.

**Comment by negativeExponent** [comment]
ok, weird. but glad you got it sorted out
