### ISSUE TITLE
Need a broken sram.dat

### ISSUE THREAD

**Issue by negativeExponent** [libretro/px68k-libretro#98]
file has to be broken in a normal way and not directly modified using human68k tools etc

This file is possible if you notice games not working when they were suppose to have worked the last time. it usually shows just a black screen with a line of japanese text (forgot to capture it when it last happened)

please upload the <system>/keropi/sram.dat. thanks.

**Comment by gingerbeardman** [comment]
Intrigued. For what?

**Comment by CadmiumRED** [comment]
[sram.zip](https://github.com/libretro/px68k-libretro/files/4079357/sram.zip)

This could be a broken sram.dat file, because any/all 3-disk X68000 games do not function for me after they're loaded once (only when sram.dat is deleted/removed/missing from the keropi directory, do 3-disk games work ONLY the first time they're loaded).  However, all 1-disk, 2-disk, and multi-disk (4-disk in this case) have worked for me with no issue whatsoever.

I've been running on the newest stable version of RetroArch 1.8.3 with the newest core update of px68k.

I'm not sure if this file would be of any help, but there it is.

**Comment by negativeExponent** [comment]
looks like this is something about SRAM start address ($ed0010, dword), resetting this to the default value of $00ed-1000 remedy this. so something is messing up reading from this

**Comment by negativeExponent** [comment]
looks like the fastest recourse for this is to have a core option to allow resetting of sram everytime, unless someone disagrees or have a better idea of what going on with it:
The issue is related to Granada and some other games that refuses to boot if sram start address is something other than the default.

**Comment by negativeExponent** [comment]
ok after 10 minutes of sleep i conclude that THIS IS A FALSE ALARM, well at least for the disk loading only black screen issue

@CadmiumRED this is still about just inserting only disk 1 on fdd0. the Eject from the Disk Control is not enough to issue a full eject. You need to use the Px68K Switch Menu (F12 or L2 on joypad), and manually have to EJECT FDD1 (if loading .m3u).

the clear sram proposal is still a valid core option to add when the screen is just black and a line of Japanese text in the middle

![Uploading x68000genericerror.png…]()

**Comment by gingerbeardman** [comment]
Is it feasible to hook the RetroArch Eject menu to the in-emu Eject?

**Comment by negativeExponent** [comment]
> Is it feasible to hook the RetroArch Eject menu to the in-emu Eject?

done https://github.com/libretro/px68k-libretro/pull/108

**Comment by gingerbeardman** [comment]
Bravo!

**Comment by negativeExponent** [comment]
an alternate fix for boot-related problems, is to have access to boot-overrides, which mean you can either boot from RAM (default behavior), ROM, HDDx, or FDDx first.

**Comment by gingerbeardman** [comment]
Possible bad sram

I am getting black screen with no text when launching games.

https://transfer.sh/11WIll/sram.dat

**Comment by negativeExponent** [comment]
i got the information i needed. closing this now...
